project:
  type: website
  output-dir: docs
  resources:
  - CNAME.txt

website:
  title: "Ryota Mugiyama"
  image: images/website.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - profile.qmd
      - research.qmd
      - lecture.qmd
      - notes.qmd
      - stata.qmd
      - r.qmd
      - blog.qmd
    background: "primary"
  favicon: website.jpg
  twitter-card: 
    image: https://mugiyama.github.io/website/website.jpg


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

