project:
  type: website
  output-dir: docs

website:
  title: "Ryota Mugiyama"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - lecture.qmd
      - stata.qmd
      - r.qmd
      - blog.qmd
  favicon: images/website.jpg
  twitter-card:
    creator: "@RyotaMugiyama"
    site: "@RyotaMugiyama"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

