---
title: "Lecture"
---

講義の情報などをまとめています。

## 2022-03　Stataによるパネル調査データ分析の実践

東京大学社会科学研究所附属社会調査・データ・アーカイブ研究センターが開講している「計量分析セミナー」で、Stataを使ったパネル調査データの分析に関する講義を行いました。パネルデータの準備（データハンドリング）に係る作業工程の考え方から、固定効果モデル、イベントの効果推定（Difference-in-differences, event study design）、さらに、よく問題になるトピックとしてランダム効果モデル、カテゴリ変数を従属変数とするモデル、脱落の問題と対処について扱っています。

[2022年度春・Stataによるパネル調査データ分析の実践](lecture/CSRDA/2023-03-09CSRDA.qmd)

## 2021-09--2022-03　Stataを用いた計量分析入門

2021年度夏から、東京大学社会科学研究所附属社会調査・データ・アーカイブ研究センターが開講している「計量分析セミナー」にて、Stataの入門的な講義を行っています。ちょっとStataを使い始めたけど、もっと効率のいい使い方について知りたい、回帰分析やロジスティック回帰分析をうまく使いこなすためにはどうすればいいか知りたい、という方を念頭において講義をしています。途中で名称が変わっていますが、内容は同じです。

[2022年度夏・Stataを用いた計量分析入門](lecture/CSRDA/2022-09-07CSRDA.qmd)

[2021年度春・Stataを用いた計量分析入門](lecture/CSRDA/2022-03-02CSRDA.qmd)

[2021年度夏・Stataを用いた計量分析の実践](lecture/CSRDA/2021-08-31CSRDA.qmd)

## 2021-09--　学習院大学法学部「社会学IV」

同内容は2022年度に日本女子大学人間社会学部、津田塾大学総合政策学部でも行いました。

### テーマ

社会階層論の現在

### 開講

学習院大学法学部 後期

### 授業の概要

高い収入や貯蓄、住宅、健康、名誉、幸福、等々、社会において希少とされる財は人びとに等しく配分されているわけではない。さらに、こうした希少財を得るためのチャンスもまた、人びとや集団の間で異なっている。希少な財の配分はどの程度偏っているのか？希少財を得る機会が個人あるいは集団間でいかに異なるのか？希少財の配分やそれを得る機会が異なるのはなぜなのか？社会階層研究はこうした不平等を研究する社会学の一分野である。

社会階層研究の扱う分野は多岐にわたるが、なかでも主要な問題とされてきたのは以下の3点である。第1に、希少財の配分がどの程度偏っているのかという結果の不平等である。所得や富の不平等の程度は国や時代によってどの程度異なるのか？不平等が拡大しているとしたらそれはなぜか？階層によって健康や家族形成のパターンはどの程度異なるのか？人びとのもつつながりは階層によってどの程度隔たっているのか？こうした問いが検討される。

第2に、希少財を得る機会がどの程度偏っているのかという機会の不平等である。親の階層とは異なる階層に移動するという世代間移動は増えているのか、減っているのか？変化しているとしたらそれはなぜか？親の階層によって教育機会の不平等が生じるのはなぜか？高い学歴を有する人がより高い階層に就くのはなぜか？これらは機会の不平等に関わる問いである。

第3に、生まれ持った属性がいかに配分や機会の不平等につながるのかという属性による不平等である。本授業ではとくにジェンダー（性別）による不平等を扱う。ジェンダー不平等は国によってどの程度違うのか？不平等の程度はどのように変化しているのか？男子は理系、女子は文系に進学しやすいのはなぜか？男性と女性が労働市場で異なる仕事に就き、異なる評価を受けるのはなぜか？家族形成がキャリアに与える影響が男女で異なるのはなぜか？こうした問いがジェンダーによる不平等という観点から検討される。

本授業では、上記3つの問題それぞれについて、実証研究の蓄積を概観することを通じて、社会学、および社会階層研究の視点から社会の不平等を捉えるための視点を身につけることを目指す。また、上記3つの問題に関して、欧米を中心に確認されてきた動向が日本においてはどの程度確認されるのかといった点についても、その成果を紹介する。これを通じて、日本の不平等の位置づけを国際的な視点から理解するとともに、不平等がいかにして生じるのか、そのメカニズムを理解することを目指す。

1.  ガイダンス

2.  結果の不平等（1）：不平等の拡大

    1.  結果の不平等の測定

    2.  所得と富の不平等：国際比較とトレンド

    3.  富裕層と貧困層

3.  結果の不平等（2）：不平等の拡大のメカニズム

    1.  なぜ不平等が拡大したのか：アメリカの場合

    2.  日本の不平等の実態とメカニズム

4.  結果の不平等（3）：階層間格差と不平等の帰結

    1.  階層の測定

    2.  階層間格差：健康と家族形成

    3.  結果の不平等の帰結

5.  結果の不平等（4）：階層分離と認識のずれ

    1.  不平等と階層分離

    2.  客観的位置と主観的認識のずれ

    3.  不平等に関する価値観

6.  機会の不平等（1）：世代間移動

    1.  社会移動の測定

    2.  職業からみる世代間移動

    3.  所得からみる世代間移動

7.  機会の不平等（2）：近代化仮説と地位達成過程

    1.  近代化仮説

    2.  地位達成過程

    3.  日本の社会移動のトレンド

8.  機会の不平等（3）：教育機会の不平等

    1.  トレンドをめぐる議論

    2.  教育機会の不平等のメカニズム

    3.  遺伝か環境か

9.  機会の不平等（4）：労働市場と機会の不平等

    1.  教育と到達階層の関係：メカニズム

    2.  日本の雇用慣行と世代内移動

    3.  出身階層の影響力の再検討

10. 属性による不平等（1）：ジェンダー不平等

    1.  ジェンダーの視点と不平等

    2.  ジェンダー不平等：国際比較とトレンド

    3.  日本のジェンダー不平等のトレンド

11. 属性による不平等（2）：教育とジェンダー

    1.  教育達成の男女差

    2.  性別専攻分離のメカニズム

12. 属性による不平等（3）：労働市場とジェンダー

    1.  賃金格差の原因を探る：要因分解

    2.  仕事の違いを測定する：性別職域分離

    3.  格差の生成過程：採用とキャリア

13. 属性による不平等（4）：家族形成とジェンダー

    1.  出産・育児と男女のキャリア

    2.  性別役割分業と結婚

14. まとめ

## 2021-04--　学習院大学法学部「社会学III」

### テーマ

現代社会学の理論的・経験的蓄積

### 開講

学習院大学法学部 前期

### 授業の概要

社会学は、人びとの集まりである社会において繰り返し観察される社会現象を正確に記述するとともに、それがなぜ生じているのかを、現象の社会的側面に着目して説明することを目的とする、社会科学の一分野である。

豊かな人と貧しい人がいるのはなぜか？太っている人とそうでない人がいるのはなぜか？似た者どうしが友人になるのはなぜか？ある小説や音楽、映画が流行するのはなぜか？社会学ではさまざまなトピック（問い）が扱われるが、社会学ではそれらを説明するにあたって、個人やモノそれ自体よりもむしろ、それらを取り巻くコンテクストの影響力に着目する。このような視点から、社会学ではこれまで多くの概念や方法が開発され、さまざまな事実が明らかにされてきた。

本授業ではこうした概念や方法、現代の社会学における理論的・経験的な蓄積を紹介し、これにふれることを通じて、社会学に通底する視点を身につけることを目指す。ひいては、身の回りのさまざまな社会現象について、社会学の視点からその実態や原因を考えられるようになることが目標である。

1.  ガイダンス
2.  問い
3.  理論
4.  方法
5.  意見
6.  規範
7.  ネットワーク
8.  集団
9.  階層と移動
10. 資源
11. 移民と統合
12. 近代化
13. 宗教
14. まとめ

### 到達目標

-   社会学的な問いの立て方を身につける。
-   社会学的な視点、理論を用いて社会現象を読み解くことができる。
-   社会学の諸概念および経験的な知見のもつ意味について理解する。

### テキスト

Tubergen, Frank van. 2020. *Introduction to Sociology.* Routledge.

## 2021-04--　学習院大学法学部「社会学演習」

### テーマ

社会的不平等に関する実証研究

### 開講

学習院大学法学部 前後期

### 授業概要

本演習の目的は、社会学の視点から、問いを設定し、仮説を立て、それに答えるために社会調査データを分析することを通じて、社会科学一般の基礎となる研究過程を体感し、かつそれを実行するためのスキルを習得することにある。社会学では、個人の行為を説明するにあたって、社会的な文脈の影響に着目する。なぜある人はお金持ちで、ある人は貧しいのか？なぜ大学に行く人と行かない人がいるのか？なぜ家事や育児にかける時間が人によって違うのか？こうした一見個人的な行為、あるいはその結果に対する説明を考え、その説明を検証するための具体的な方法を身につけることを目指す。

社会の実態を記述するために最も基本的な方法の一つが、社会調査データの分析である。本演習では、実際にこうした調査データを用い、統計ソフトを用いて分析する方法について学習する。先行研究をもとに問いを立て、論理的に仮説を導き、データを用いて仮説を検証するという一連の作業を通じて、実証的な研究を行うためのスキルを身につける。こうしたスキルは、直接研究には携わらないとしても、今後の仕事や生活で必ず役に立つだろう。

前期は社会学に関連する基礎的な文献および実証研究論文の購読と、統計分析の方法およびそれを具体的に実行するための統計ソフト（RおよびRStudio）の使い方の学習を並行して進める。文献の購読に関しては、はじめに少人数のグループに分かれて内容や疑問点について話し合った後、議論の共有を行う。有意義な議論を行うため、参加者は全員がテキストを事前に読んでくる必要がある。統計分析の方法に関する文献については、各自事前に該当箇所を読んだうえで、一通り書かれたコードを実行してくる。こちらも各自が文献を読んでいることを前提に、授業では疑問点を解消することを中心とする。前期末には後期の個人研究に向けた研究計画の書き方やデータの紹介を行う。これを参考にしながら、夏期休暇中には各自で研究計画を作成・提出する。

後期は各自の研究報告およびレポート執筆のための作業を中心とする。報告者は事前の十分な準備が必要となる。研究課題は社会学、なかでも社会階層、不平等、労働、家族、教育、等々にかかわるテーマでのレポート執筆を期待するが、とくにこのテーマでなければならないといった制限はない。統計分析に使用する社会調査データとしては、日本版総合的社会調査（Japan General Social Survey, JGSS. <https://jgss.daishodai.ac.jp/surveys/sur_top.html>）を予定している。別の調査データ等の使用については妨げるものではないが、別途使用に際して手続きが必要な場合があるので、教員に相談すること。文献2の付録にはJGSSのほか社会調査データの説明がいくつか載っている。なお受講人数によっては、1人ではなく2--3人のグループを作ることも検討する。複数回の研究報告を通じて研究内容をブラッシュアップし、研究論文としても良質のレポートを執筆することを目指す。

### 到達目標

1.  社会学の視点から問いを設定し、仮説を立てられるようになる。

2.  社会調査データの分析方法を身につける。

3.  実証研究による報告論文（レポート）を書くことができる。
