---
title: "Notes"
date: "2025-08-18"
---

主に計量分析の手法やプログラムに関するメモをアップロードしていく予定です。

## [論文輪読会レジュメ]

論文の輪読会で使ったレジュメを不定期に更新します。

- [Martin-Caughey, Ananda. 2021. "What’s in an Occupation? Investigating Within-Occupation Variation and Gender Segregation Using Job Titles and Task Descriptions." *American Sociological Review* 86(5):960–99.](notes/resume/2022-04-23-RCIS-mugiyama.pdf)
- [Torche, Florencia, and Alejandra Abufhele. 2021. "The Normativity of Marriage and the Marriage Premium for Children’s Outcomes." *American Journal of Sociology* 126(4):931–68.](notes/resume/2022-06-24-RCIS-mugiyama.pdf)
- [Chetty, Raj et al. 2022. "Social Capital I: Measurement and Associations with Economic Mobility." *Nature*. http://dx.doi.org/10.1038/s41586-022-04996-4](notes/resume/2022-09-17-RCIS-mugiyama.pdf)
- [Jackson, Margot I., and Daniel Schneider. 2022. "Public Investments and Class Gaps in Parents’ Developmental Expenditures." *American Sociological Review* 87(1):105–42.](notes/resume/2022-12-10-RCIS-mugiyama.pdf)
- [Gong, S., & Wang, S. (2022). Family Policy Awareness and Marital Intentions: A National Survey Experimental Study. Demography, 59(1), 247–266.](notes/resume/2023-04-29-RCIS-mugiyama.pdf)
- [Wilmers, Nathan, and Clem Aeppli. 2021. "Consolidated Advantage: New Organizational Dynamics of Wage Inequality." *American Sociological Review* 86(6):1100–1130.](notes/resume/2023-09-12-RCIS-mugiyama.pdf)
- [Cheng, S., & Song, X. (2019). Linked Lives, Linked Trajectories: Intergenerational Association of Intragenerational Income Mobility. *American Sociological Review*, 84(6), 1037–1068.](notes/resume/2024-03-12-RCIS-mugiyama.pdf)
- [Labussière, M., & Bol, T. (2024). Are occupations "bundles of skills"? Identifying latent skill profiles in the labor market using topic modeling. *SocArXiv*. https://doi.org/10.31219/osf.io/5zwmt](notes/resume/2024-07-17-RCIS-mugiyama.pdf)
- [Godechot, Olivier, Donald Tomaskovic-Devey, István Boza, Lasse Folke Henriksen, Are Skeie Hermansen, Feng Hou, Jiwook Jung, Naomi Kodama, Alena Křížková, Zoltán Lippényi, Silvia Maja Melzer, Eunmi Mun, Halil Sabanci, Max Thaning, Paula Apascaritei, Dustin Avent-Holt, Nina Bandelj, Alexis Baudour, David Cort, Marta M. Elvira, Gergely Hajdu, Aleksandra Kanjuo-Mrčela, Joseph King, Andrew Penner, Trond Petersen, Andreja Poje, Anthony Rainey, Mirna Safi, and Matthew Soener. 2024. "The Great Separation: Top Earner Segregation at Work in Advanced Capitalist Economies." *American Journal of Sociology* 130(2):439–95.](notes/resume/2024-10-09-RCIS-mugiyama.pdf)
- [Kim, C. (2025). Culture and Immigrant Selectivity in Shaping Asian American Education: Evidence from Historical Census Data. *American Sociological Review*, 0(0). https://doi.org/10.1177/00031224251325259](notes/resume/2025-05-02-RCIS-mugiyama.pdf)


## [SSM職歴データのパーソンイヤーデータへの変換](https://github.com/ryotamugiyama/ssm2015personyear)

SSM調査データをパーソンイヤーデータに変換する際のデータ加工の考え方、いくつかの分析例、およびStataのdo-fileとRのコードをアップロードしています。2024年5月31日の2025年SSM調査研究会にて報告した内容ですが、広く研究会外でSSM調査データを使う方の目的に供するために公開しています。コードに誤りなどを見つけた場合はお知らせいただければと思います。

last update: 2024-06-11

## [決定係数の要因分解](notes/DecomposingRsquared.html)

決定係数は(1) 独立変数の限界効果、 (2) 独立変数の分散および共分散、(3) 従属変数の分散、の3つの要因に左右されます。2つの異なるサンプル間の決定係数の違いが何によって生じているかを考えたいときには、要因分解の方法が有用です。そこで要因分解の式を考えました。

資料中の方法を再現するStataコード：

``` stata
sysuse auto, clear

gen y = mpg

*** Estimate linear regression for non-foreign cars.
reg y price weight if foreign == 0
predict yhat0

*** Estimate linear regression for foreign cars.
reg y price weight if foreign == 1
predict yhat1

collapse (sd) y yhat1 yhat0, by(foreign)

*** Generate variance of y.
replace y = y^2

forvalues i = 0/1{
    replace yhat`i' = yhat`i'^2
    gen rsq`i' = yhat`i' / y
    rename yhat`i' yhat_`i'x_
    rename rsq`i' rsq`i'x_
}

gen id = 1
reshape wide y* rsq*, i(id) j(foreign)

*** Observed R-squared for sample 0 and sample 1.
gen obsrsq0 = rsq0x_0
gen obsrsq1 = rsq1x_1

*** comp1: structural change.
gen comp1 = ln(yhat_1x_1) - ln(yhat_0x_1)

*** comp2: change in independent variables.
gen comp2 = ln(yhat_0x_1) - ln(yhat_0x_0)

*** comp3: change in dependent variable.
gen comp3 = ln(y0) - ln(y1)

*** Check: sum of comps is the same with log of observed R-sq?
gen logrsq = ln(rsq1x_1 / rsq0x_0)
gen sumcomp = comp1 + comp2 + comp3

tabstat logrsq sumcomp comp1 comp2 comp3
```

（2019/9/6→2022/09/19移行）

## [相関係数と散布図](notes/corr_scatter.html)

Rの練習の一環で、よく教科書に載っている「相関係数が◯◯のときの散布図」をRで作る際のスクリプトを書きました。

（2018/3/4 upload, 2018/3/9 revised→2022/09/19移行）

## [階層ベイズモデルを実装する](notes/hierarchicalbeyes.html)

「岩波データサイエンスをざっくり読む会」第2回で使用する発表資料です。マルチレベルモデルの基礎と、これをベイズで推定するための方法を解説しています。RおよびRstanを使用しています。まだ途中ですが、ひとまずアップロードしています。

（2017/9/25 upload→2022/09/16移行）

## [固定効果モデルに2乗項を投入する](notes/squareterm_fe.html)

固定効果モデルに2乗項を投入することをどのように考えればいいのか、ということについてのメモです。

（2017/11/20 upload→2022/09/16移行）

## [イベントヒストリー分析のためのデータ加工とモデル選択](notes/eventhistory.pdf)

イベントヒストリー分析のために必要なデータの形式とその加工の方法、分析の際に考慮すべきことについて、具体的な手順（パーソン・ピリオドデータの作成とモデルの選択）を紹介しています。2016年1月9日の計量研究会にて発表いたしました。数式やシンタックスについて、間違いや非効率的な部分などがあるかもしれませんが、ご了承ください。

（2016/01/09 upload, 2016/02/09 コードに若干ミスがあったのを修正→2022/09/19移行）

## [社会学のための統計分析基礎：SPSSを用いて](notes/2016-05-17TA_SPSS.pdf)

所属研究室にて、社会調査実習という学部生・院生向けの授業のTAを担当しています。5/17の授業にて、統計分析の基礎についての授業を担当した際に用いた資料です。SPSSを使って、データハンドリングの仕方、1変量分布・2変量関連の検討の仕方について解説しています。推測統計の話はあえて行っていません。 （2016/05/19 upload） （2016/05/27 p.27についてご指摘頂いたので修正。ありがとうございました。）

[第2弾](notes/2016-11-08TA_SPSS2.pdf)をアップロードしました。推測統計、2変量関連、多変量解析の考え方と回帰分析の基礎について解説しています。（2016/11/08）

（→2022/09/19移行）

## [逆ミルズ比を図で理解する](notes/millsratio.html)

サンプルセレクションモデルで頻出する逆ミルズ比について、図で理解できるようにいろいろと工夫してみた、という記事です。R markdownで作成しました。（2016/11/28 upload）

（→2023/04/10移行）