---
title: "Occupation"
date: "2024-04-03"
---

職業分類の対応関係に関する資料を随時アップロードします。

## 国勢調査の1980--2020年統合職業分類

国勢調査は各年ごとに職業分類の変更があります。とくに2005年から2010年にかけては大規模な変更が行われ、その前後の比較がそのままでは難しくなっています。この期間の改定の具体的内容については「[2010年国勢調査に用いる職業分類](https://www.stat.go.jp/data/kokusei/2010/users-g/pdf/syokugyo.pdf)」にくわしく記載されています。　

| 調査年               | 小分類数\* | 備考                                     |
|------------------|------------------------|-------------------------------|
| 1980年               | 284        |                                          |
| 1985年               | 292        |                                          |
| 1990年               | 293        |                                          |
| 1995年               | 293        | 1990年と同一分類                         |
| 2000年               | 292        |                                          |
| 2005年               | 273        |                                          |
| 2010年               | 231        | 日本標準職業分類の改定に伴う大規模な変更 |
| 2015年               | 231        | 2010年と同一分類                         |
| 2020年               | 231        | 2010年と同一分類                         |
| 1980--2020年統合分類 | 163        | 麦山作成                                 |

\*小分類数は「分類不能の職業」を除いた数。

この問題に対処すべく、1980--2020年で比較可能となるよう統合分類を作成しました。統合分類は「分類不能の職業」を除き、163の職業からなります。実際には小分類内の職業の細かな入れ替わりなどがあり、本当に厳密な意味での比較は難しいのですが、それを踏まえたうえで使用するのがよいと思います。

-   小松恭子・麦山亮太，2024，「[タスクの日米比較からみた日本の労働市場の特徴と変化：日本版O-NETと国勢調査（1980～2020年）を使用した分析から得られた示唆](https://www.jil.go.jp/institute/siryo/2024/280.html)」『JILPT 資料シリーズ』No.280．付属資料4を参照。

過去には、1980--2005年の国勢調査職業分類を統合して性別職域分離の趨勢を検討した研究も行いました。

-   打越文弥・麦山亮太，2020，「 [日本における性別職域分離の趨勢：1980–2005年国勢調査集計データを用いた要因分解](https://doi.org/10.24454/jps.1901001)」『人口学研究』56:9--23．

## 国勢調査に用いる職業分類と日本版O-NETとのマッチング

[2010年国勢調査に用いる職業分類](https://www.stat.go.jp/data/kokusei/2010/users-g/pdf/syokugyo.pdf)と[日本版O-NET](https://shigoto.mhlw.go.jp/User/)の職業をマッチングして、国勢調査の職業に 対して日本版O-NETの数値指標を与えるためのマッチング表を作成しました。さらに、2005年国勢調査に用いる職業分類と日本版O-NETとのマッチング表を作成しています。

-   小松恭子・麦山亮太，2021，「[日本版O-NETの数値情報を使用した応用研究の可能性： タスクのトレンド分析を一例として](https://www.jil.go.jp/institute/discussion/2021/21-11.html)」『JILPT Discussion Paper』21-11．

なお、2005年国勢調査に用いる職業分類はWeb上に「国勢調査に用いる職業分類」冊子のpdfが公開されていないので、図書館などで入手する必要があります。

最新版（2024年3月30日時点）では、日本版O-NET ver 4.00を参照して、2010年国勢調査に用いる職業分類と日本版O-NETのマッチング表を作成しています。

-   小松恭子・麦山亮太，2024，「[タスクの日米比較からみた日本の労働市場の特徴と変化：日本版O-NETと国勢調査（1980～2020年）を使用した分析から得られた示唆](https://www.jil.go.jp/institute/siryo/2024/280.html)」『JILPT 資料シリーズ』No.280．付属資料4を参照。

## 1995年SSM職業分類と日本版O-NETとのマッチング

1995年SSM職業分類に700番台の職業と800番台の職業を追加した職業分類（SSM1995--2015, JGSS2000--2018, JLPSで使用されています）と、[日本版O-NET](https://shigoto.mhlw.go.jp/User/)の職業をマッチングして、SSM職業分類に対して日本版O-NETの数値指標を与えるためのマッチング表を作成しました。

麦山亮太・田上皓大，2024（近刊），「SSM職業分類への日本版O-NETのマッチングと応用：スキルと賃金の関連を事例に」『理論と方法』39(1)．

マッチング表は[田上さんのGitHub](https://github.com/kota-tagami/matching_onet_ssm)にアップロードしています。

## 1995年SSM職業分類関連の諸指標まとめ

社会学者が作成した1995年SSM職業分類（およびその周辺情報）から作成できる諸指標の書誌情報をまとめています。

EGP階級分類

-   鹿又伸夫・田辺俊介・竹ノ下弘久，2008，「SSM職業分類と階層指標：EGP階級分類・SIOPS・ISEIへの変換」前田忠彦編『2005年SSM調査シリーズ12：社会調査における測定と分析をめぐる諸問題』2005年社会階層と社会移動調査研究会，
-   竹ノ下弘久・田辺俊介・鹿又伸夫，2007，「[階層移動の国際比較に向けての階層カテゴリーの構成：SSM職業小分類のEGP分類への変換とその方法](https://doi.org/10.14945/00008218)」『人文論集』 58(2):17--42.
-   田辺俊介，2006，「ISCOとSSM職業分類の相違点の検討：国際比較調査における職業データに関する研究ノート」『社会学論考』27:53--78.

日本版社会経済指標（SEI）、社会的地位指標（SSI）

-   Fujihara, Sho. 2020. "Socio-Economic Standing and Social Status in Contemporary Japan: Scale Constructions and Their Applications." *European Sociological Review* 36(4): 548--61. [GitHub](https://github.com/ShoFujihara/OccupationalScales)

職業威信スコア

-   都築一治編，1998，『職業評価の構造と職業威信スコア』1995年SSM調査研究会．

マイクロクラス

-   Jonsson, Jan O., Matthew Di Carlo, Mary C. Brinton, David B. Grusky, and Reinhard Pollak. 2009. "Microclass Mobility: Social Reproduction in Four Countries." *American Journal of Sociology* 114(4):977--1036.
-   三輪哲，2009，「[社会的格差をとらえるためのマイクロクラス・アプローチ：JGSS累積データ2000-2006による計量的分析](https://jgss.daishodai.ac.jp/research/monographs/jgssm8/jgssm8_01.pdf)」『日本版 General Social Surveys』 研究論文集』8: 1--12．

仕事の複雑性スコア

（2024-04-03 Web上からスコアの情報が見つけられなくなっている？）

-   長松奈美江・阪口祐介・太郎丸博，2009，「[仕事の複雑性スコアの構成：職務内容を反映した職業指標の提案](https://doi.org/10.11218/ojjams.24.77)」『理論と方法』24(1):77--93.

Oeschの階級分類

-   長松奈美江，2021，「対人サービス労働者の「仕事の質」」白波瀬佐和子監修，渡邊勉・吉川徹・佐藤嘉倫（編）『少子高齢社会の階層構造　第2巻　人生中期の階層構造』東京大学出版会，53-66．

SSM職業8分類

- [SSM職業小分類（追加コード含む）をSSM職業8分類に変換するStataシンタックス
](../blog/2016-04-07-ssmocc8.html)を参照。

## 1955年SSM職業分類を1995年SSM職業分類に変換する

**準備中**

## 全国就業実態パネル調査の職業分類と日本版O-NETとのマッチング

リクルートワークス研究所の実施している「[全国就業実態パネル調査](https://www.works-i.com/surveys/panel_surveys.html)」は2017−−2022年は224（分類不能の職業含む）、2023年は214（分類不能の職業含む）の職業小分類をプルダウン形式で回答者に提示し、回答者が選択する形式で職業小分類を聴取しています。国勢調査や就業構造基本調査、賃金構造基本統計調査、あるいはSSM調査等の社会調査で行われている自由記述のアフターコーディングが行われていない分正確さという面では劣りますが、サンプルサイズが他の社会調査と比べて大きく、活用しない手はありません。

全国就業実態パネル調査の2017--2022年職業分類、および2023年職業分類と日本版O-NETの職業をマッチングして、各職業分類に対して日本版O-NETの数値指標を与えるためのマッチング表を作成しました。**説明文書は作成中**

2017--2022年職業分類と日本版O-NETをマッチングしたデータを使った論文を公刊しています。

-   麦山亮太・小松恭子，2023，「[テレワーク制度適用の企業規模・雇用形態間格差の要因：新型コロナウイルス感染症流行前後の比較分析](https://www.jil.go.jp/institute/zassi/backnumber/2023/05/pdf/087-102.pdf)」『日本労働研究雑誌』754: 87--102．

全国就業実態パネル調査自体は2016年から実施されているのですが、2016年はそれ以降とは職業分類が異なっておりまた別にコーディングの必要があります。自分は2016年データを使用しなかった関係でこのマッチングはやっていません。

## 全国就業実態パネル調査の職業分類からISCO-08を介してEGP階級分類を作成する

全国就業実態パネル調査の2017--2022年職業分類、および2023年職業分類に対してISCO-08コードを割り当て、Stataの[iscogen](https://ideas.repec.org/c/boc/bocode/s458665.html)コマンドを使ってISCO-88へと変換し、EGP階級分類へと変換するための対応表とコードを作成しました。**説明文書は作成中**

ここでISCO-08コードを使っているのはあくまでEGP階級分類に到達するための途中段階として利用しているに過ぎず、全国就業実態パネル調査の職業分類をISCO-08コードに割り当ててそれ自体を使って分析することは意図していない点に注意してください。