---
title: "Profile"
---

Followed by English translation.

### 職歴

2021年4月--現在　学習院大学法学部政治学科 准教授

2019年4月--2021年3月　日本学術振興会特別研究員PD（一橋大学経済研究所）

2017年4月--2019年3月　日本学術振興会特別研究員DC2

### 学歴

2016年4月--2019年3月　東京大学大学院人文社会系研究科 社会文化研究専攻 社会学専門分野博士課程，博士（社会学）

2014年4月--2016年3月　東京大学大学院人文社会系研究科 社会文化研究専攻 社会学専門分野修士課程，修士（社会学）

2012年4月--2014年3月　東京大学文学部 行動文化学科 社会学専修課程，学士（文学）

2010年4月--2012年3月　東京大学教養学部 文科一類

### Positions

Apr 2021--Current: Faculty of Law, Department of Political Studies, Gakushuin University.

Apr 2019--Mar 2021: Post-doctoral Research Fellow (PD), Japan Society for the Promotion of Science (Institute of Economic Research, Hitotsubashi University).

Apr 2019--Mar 2021: Pre-doctoral Research Fellow (DC2), Japan Society for the Promotion of Science.

### Education

Apr 2016--Mar 2019: Ph.D. in Sociology, Department of Sociology, University of Tokyo. 

Apr 2014--Mar 2016: M.A. in Sociology, Department of Sociology, University of Tokyo. 

Apr 2010--Mar 2014: B.A. in Letters, Faculty of Letters, University of Tokyo.