---
title: "Research"
date: "today"
---

Other research publications can also be found on the following pages.

-   [googlescholar](https://scholar.google.co.jp/citations?user=oJnisc0AAAAJ)
-   [ORCID](https://orcid.org/0000-0002-6157-5575)
-   [researchmap](https://researchmap.jp/mugiyama) (mainly in Japanese)

## Peer-reviewed paper

### in English

Mogi, Ryohei, Ryota Mugiyama, and Alyce Raybould. 2025. "[Exposure to Non-partnership and Fertility Desires among Childless Population in Japan](https://doi.org/10.1093/sf/soaf123)." *Social Forces.* Advance Access.

Mugiyama, Ryota. 2025. "[Decomposing Delayed First Marriage and Birth across Cohorts: The Role of Increased Employment Instability among Men in Japan](https://doi.org/10.4054/DemRes.2025.52.21)." *Demographic Research.* 52: 635--688.

Mugiyama, Ryota. 2024. "[Disaggregating the Relationship between Precarious Employment and Delayed Marriage in Japan: Incorporating Non-cohabiting Partnerships](https://doi.org/10.1016/j.ssresearch.2024.103093)." *Social Science Research.* 124: 103093.

Mogi, Ryohei, Ryota Mugiyama and Giammarco Alderotti. 2024. "[Employment Uncertainty and Non-coresidential Partnership in Very Low Fertility Countries: Italy and Japan](https://doi.org/10.20377/jfr-953)." *Journal of Family Research.* 36: 160--177.

Mugiyama, Ryota. 2024. "[Cohort Change in the Educational Gradient in Women's Employment Around Childbirth in Japan](https://doi.org/10.1016/j.rssm.2023.100885)." *Research in Social Stratification and Mobility.* 89: 100885.

Çineli, Beyda and Ryota Mugiyama. 2023. "[Money Management over the Course of Marriage: Parenthood, Employment and Household Financial Organization in Japan](https://doi.org/10.1016/j.alcr.2023.100544)." *Advances in Life Course Research.* 56: 100544.

Igarashi, Akira and Ryota Mugiyama. 2023. "[Whose Tastes Matter? Discrimination against Immigrants in the Japanese Labour Market](https://doi.org/10.1080/1369183X.2022.2163230)." *Journal of Ethnic and Migration Studies.* 49(13): 3365--3388.

Mugiyama, Ryota and Kohei Toyonaga. 2022. "[Role of Cohort Size in Trends in Class and Occupational Returns to Education at First Job: The Case of Japan](https://doi.org/10.1093/esr/jcab037)." *European Sociological Review.* 38(2): 269--285.

### in Japanese

<!--- 
麦山亮太・林愛子，xxxx，「専攻間賃金格差の男女比較分析：年齢による違いに着目して」『日本労働研究雑誌』
小松恭子・麦山亮太，2026，「1980～2020 年の日本の労働市場におけるタスク分布の変化：産業構造の変化とICT 導入の影響」『日本労働研究雑誌』
--->

麦山亮太・大里蒼一郎，2024，「[地域の図書館普及が子どもの学習時間に与える影響とその階層差](https://doi.org/10.11218/ojjams.39.19)」『理論と方法』39(1): 19--34．

麦山亮太・田上皓大，2024，「[SSM職業分類への日本版O-NETのマッチングと応用：スキルと賃金の関連を事例に](https://doi.org/10.11218/ojjams.39.64)」『理論と方法』39(1): 64--76．[SSM-ONET対応表へのリンク](https://github.com/kota-tagami/matching_onet_ssm)

麦山亮太・小松恭子，2023，「[テレワーク制度適用の企業規模・雇用形態間格差の要因：新型コロナウイルス感染症流行前後の比較分析](https://www.jil.go.jp/institute/zassi/backnumber/2023/05/index.html)」『日本労働研究雑誌』754: 87–102．

五十嵐彰・麦山亮太，2023，「[サーベイ実験を用いた日本における外国人雇用差別の検証：企業属性による異質性](https://doi.org/10.11218/ojjams.38.44)」『理論と方法』38(1): 44--58．

麦山亮太，2022，「[出産・育児期における女性就業とその学歴差の長期趨勢：雇用労働力化に着目して](https://doi.org/10.4057/jsr.73.86)」『社会学評論』73(2): 86--102．[補足表](research/mugiyama2022jsr_request.pdf)

打越文弥・麦山亮太・小松恭子，2021，「[職域分離とスキルからみる労働市場のジェンダー格差：日本版O-NET・国勢調査マッチングデータから得られる示唆](https://doi.org/10.11218/ojjams.36.65)」『理論と方法』36(1): 65--82．（特集論文）

打越文弥・麦山亮太，2020，「[日本における性別職域分離の趨勢：1980--2005年国勢調査集計データを用いた要因分解](https://doi.org/10.24454/jps.1901001)」『人口学研究』56: 9--23．

麦山亮太・西澤和也，2017，「[大企業と中小企業が新卒者に求める能力は異なるか：求人情報サイトへのトピックモデルの適用](https://doi.org/10.11218/ojjams.32.214)」『理論と方法』32(2): 214--227．

麦山亮太，2017，「[職業経歴と結婚への移行：雇用形態・職種・企業規模と地位変化の効果における男女差](https://doi.org/10.4234/jjoffamilysociology.29.129)」『家族社会学研究』29(2): 129--141．

麦山亮太，2017，「[キャリアの中断が生み出す格差：正規雇用獲得への持続的影響に着目して](https://doi.org/10.4057/jsr.68.248)」『社会学評論』68(2): 248--264．

麦山亮太，2016，「[結婚は職業キャリアにいかなる影響を与えるのか？：無業・管理職への移動に関する男女比較分析](https://doi.org/10.4234/jjoffamilysociology.28.122)」『家族社会学研究』28(2): 122--135．

## Work in progress

### Social mobility

Multigenerational Perspective on Trends in the Inequality of Educational Opportunity in Japan (with Aguru Ishibashi)

- 2024-04-20 Presented at PAA Annual Meeting  at Hyatt Regency Columbus, Ohio. [poster](https://researchmap.jp/mugiyama/presentations/45595571)
- 2023-10-25 Working paper is found here. [paper](https://csrda.iss.u-tokyo.ac.jp/international/dp/No.63.pdf)
- 2023-08-15 Presented at RC28 Summer Meeting at University of Michigan. [slide](https://researchmap.jp/mugiyama/presentations/41971649)
- 2023-03-08 Presented at JAMS 74th Meeting at Tsukuba University. [slide](https://researchmap.jp/mugiyama/presentations/41548059)

Does Educational Expansion Weaken the Equalizing Power of College? Trends in Social Origin Differentials in Occupational Destination in Japan (with Kohei Toyonaga)

- 2022-08-13 Presented at RC28 Summer Meeting at University of Notre Dame. [slide](https://researchmap.jp/mugiyama/presentations/38562818)

Changing University Accessibility and Inequality of Educational Opportunity in Japan (with Kohei Toyonaga)

-   2024-12-17 Working paper is found here. [paper](https://csrda.iss.u-tokyo.ac.jp/international/dp/No.112.pdf)
-   2023-10-09 Presented at JSS 96th Annual Meeting at Rissho University.
-   2023-07-15 Presented at READI 1st Annual Conference at University of Tokyo. [slide](https://researchmap.jp/mugiyama/presentations/42557130)
-   2022-08-28 Presented at JAMS 73rd Meeting.  [slide](https://researchmap.jp/mugiyama/presentations/38562818)

Social Origin Earnings Gap in Japan: Differential Effects by Class Destination

- 2024-09-13 Working paper is found here. [peper](https://csrda.iss.u-tokyo.ac.jp/international/dp/No.97.pdf)
- 2024-05-18 Presented at RC28 Spring Meeting at NYU Shanghai. [slide](https://researchmap.jp/mugiyama/presentations/45741717)
- 2024-03-16 Presented at JAMS 76th Meeting at Osaka University. [slide](https://researchmap.jp/mugiyama/presentations/45509862)

Intergenerational Educational Mobility and Subjective Social Status (with Aram Kwon)

- 2025-03-27 Presented at RC28 Spring Meeting at University of Milan.
- 2025-03-21 Presented at CSRDA Secondary Data Analysis Workshop.

Intergenerational Educational Mobility in 21st Century Japan: Changing Roles of Fathers and Mothers? (with Aguru Ishibashi) 

<!---- 
- 2025-11-xx Presented at JSS 86th Annual Meeting at Hitotsubashi University. [slide](https://researchmap.jp/mugiyama/presentations/49369343) 
---->
- 2025-08-07 Presented at RC28 2025 Summer Meeting at UCLA. 
- 2025-03-21 Presented at CSRDA Secondary Data Analysis Workshop. [slide](https://researchmap.jp/mugiyama/presentations/49071062) 

<!---- 
Downward Mobility and Loneliness: Consequences of Intergenerational Educational Mobility in Japan (with Aram Kwon and Takahiro Tabuchi)

- 2024-04-11 Working paper is found here. [paper](https://csrda.iss.u-tokyo.ac.jp/international/dp/No.83.pdf)
- 2023-08-15 Presented at RC28 Summer Meeting at University of Michigan. [poster](https://researchmap.jp/mugiyama/presentations/41971642)
---->

### Labor market inequality

Rising socioeconomic inequality in access to remote work following the COVID-19 outbreak in Japan
 (with Kyoko Komatsu)

- 2024-10-25 Presented at CFPR Lunchtime Seminar Series, National University of Singapore
 [slide](https://researchmap.jp/mugiyama/presentations/47363765)
- 2023-08-24 Working paper is found here. [paper](https://csrda.iss.u-tokyo.ac.jp/international/dp/No.56.pdf)
- 2022-11-12 Presented at JSS 95th Annual Meeting at Otemon Gakuin University. [slide](https://researchmap.jp/mugiyama/presentations/40475337)

Trends in Task Distribution in Japan, 1980--2020: Evidence from the Occupational Information Network of Japan and the Population Census (with Kyoko Komatsu)

- 2025-02-28 Discussion paper is found here (in Japanese). [website](https://www.jil.go.jp/institute/discussion/2025/25-01.html)

Revisiting Motherhood Wage Penalty Following First birth in Japan: Unpacking the Sources

- 2025-07-18 Presented at READI 3rd Annual Conference at Yonsei University. [slide](https://researchmap.jp/mugiyama/presentations/47722325)
- 2025-05-16 Presented at Conference on Family Conflict and Dynamics in East Asia at the University of Hong Kong Research Hub of Population Studies. [slide](https://researchmap.jp/mugiyama/presentations/49887140)
- 2024-08-06 Presented at RC28 2024 Summer Meeting at Brown University. [slide](https://researchmap.jp/mugiyama/presentations/45778764)
- 2024-06-28 Working paper is found here. [paper](https://csrda.iss.u-tokyo.ac.jp/international/dp/No.87.pdf)
- 2024-06-09 Presented at PAoJ 76th Annual Meeting at Chuo University. [slide](https://researchmap.jp/mugiyama/presentations/45741726)

Task Variety and Its Earnings Returns Across Countries: Evidence from PIAAC (with Shin Arita)

- 2025-07-11 Presented at Society for the Advancement of Socio-Economics (SASE) 2025 Annual Meeting at Palais des Congrès, Montréal, Québec. 
- 2024-08-30 Presented at JAMS 77th Annual Meeting at Tohoku University. [slide](https://researchmap.jp/mugiyama/presentations/46844602)

The Weight of Gendered Expectation: Pre-birth Endorsement of Intensive Mothering Ideologies and the Motherhood Penalty (with Rantaro Nasu and Yuriko Morikawa)

- 2025-08-28 Presented at JAMS 79th Meeting at Kwansei Gakuin University. [slide](https://researchmap.jp/mugiyama/presentations/49886946)
- 2025-06-28 Presented at Social Stratification and Mobility Summer International Workshop.

<!---- 
Trends in Occupational Gender Segregation in Japan, 1980--2020 (with Fumiya Uchikoshi) 
--->

### Family Demography 

Revisiting the Relationship between Marriage and Childbearing in Low-Fertility East Asia: Evidence from Japan (with Fumiya Uchikoshi, Shohei Yoda, and James M. Raymo)

- 2024-04-18 Presented at PAA 2024 Annual Meeting at Hyatt Regency Columbus, Ohio. 
- 2023-09-02 Presented at JSFS 33rd Annual Meeting at Kobe University.

Does Policy Affect Fertility and Marriage Desires Among Never-Married Childless People? A Factorial Survey Experiment (with Shin Okubo, Kota Toma, Shohei Yoda, and Shigeki Matsuda)

- 2024-11-09 Presented at JSS 97th Annual Meeting at Kyoto Sangyo University. [slide](https://researchmap.jp/mugiyama/presentations/46363891)
- 2024-07-29 Presented at READI 2nd Meeting at Peking University. [slide](https://researchmap.jp/mugiyama/presentations/46241948)
- 2024-03-17 Presented at JAMS 76th Meeting at Osaka University. [slide](https://researchmap.jp/mugiyama/presentations/45509867)

The Cost of Raising Children and Family Intentions and Desires: A Survey Experiment Approach Using Information Intervention (with Fumiya Uchikoshi)

- 2025-04-11 Presented at PAA 2025 Annual Meeting at Marriott Marquis Washington DC. [slide](https://researchmap.jp/mugiyama/presentations/47722304)

Gender-role Attitudes and Transition to Marriage and Parenthood in Japan

- 2025-06-14 Presented at 2025 Annual Meeting of Life Course Transitions in East Asia. [slide](https://researchmap.jp/mugiyama/presentations/50233960)

<!--- Revisiting the Attitudinal Link between Marriage and Childbearing in Low-Fertility East Asia: Evidence from Japan (with Haruki Sugimoto, Fumiya Uchikoshi, and Shohei Yoda) --->

<!--- Socio-economic status and transition to non-cohabiting partnership in East Asia and Europe (with Ryohei Mogi, Inhee Han, Alyce Raybould, Lisa Schmid, and Jiajie Zhang --->

<!---- Trends in Sex Segregation by Field of Study in Japan, 2003--2023 (with Fumiya Uchikoshi, Megumi Oguro, and Kohei Toyonaga) --->

## Book chapter

<!----
麦山亮太，2026，「産業構造の変化と労働」編『産業と労働の社会学事典』丸善出版，xxx--xxx．
--->

麦山亮太，2023，「男性の職業・家族キャリア」家族社会学会編『[家族社会学事典](https://www.maruzen-publishing.co.jp/item/b305112.html)』丸善出版，460--461．

打越文弥・麦山亮太，2022，「性別職域分離」数理社会学会監修『[数理社会学事典](https://www.maruzen-publishing.co.jp/item/?book_no=304405)』丸善出版，330--333．

麦山亮太・吉川裕嗣，2015，「東アジアの学生の意識にみるアジア統合の展望：アジア人意識と脅威認識を軸として」[園田茂人編『アジア比較社会研究のフロンティアⅢ 連携と離反の東アジア』勁草書房](http://www.keisoshobo.co.jp/book/b193739.html)，231--255．

## Miscs

<!--- 
麦山亮太・平松誠・コンアラン・那須蘭太郎・吉田航，2025，「社会調査データの合併による二次分析研究の刷新：データ合併の作業手順と今後の調査実施・データ整備に向けた示唆」SSJDA Research Paper Series.
麦山亮太，2025，「」『季刊個人金融』
--->

麦山亮太，2024，「[社会階層研究の現在：労働関連分野を中心に](https://www.jil.go.jp/institute/zassi/backnumber/2024/04/index.html)」『日本労働研究雑誌』765: 78--83．

麦山亮太，2022，「[文献紹介 渡邊勉・吉川徹・佐藤嘉倫編『少子高齢社会の階層構造2 人生中期の階層構造』](https://doi.org/10.4234/jjoffamilysociology.34.152)」『家族社会学研究』34(2): 152．

Komatsu, Kyoko and Ryota Mugiyama. 2022. "[Trends in Task Distribution in Japan, 1990--2015: Evidence from the Occupational Information Network of Japan and the Population Census Data](https://www.jil.go.jp/english/jli/documents/2022/037-06.pdf)." *Japan Labor Issues*. 37(6): 55--70.

麦山亮太，2021，「[地位の経歴からみる不平等の生成過程](https://doi.org/10.11218/ojjams.36.4)」『理論と方法』36(2): 4--15．

麦山亮太，2018，「[文献紹介 吉川徹著『日本の分断：切り離される非大卒若者たち』](https://doi.org/10.4234/jjoffamilysociology.30.270)」『家族社会学研究』30(2): 270．
