---
title: "大学院進学・研究生希望の学生の方へ"
date: "2024-04-28"
---

この文章は、学習院大学大学院政治学研究科（修士課程または博士課程）に進学したい、あるいは大学院への進学を前提に学部の研究生として入学したい、とくにそこで私（麦山）を指導教員としたいという学生の方向けに書かれています。

## 一般的な事項

### 専門領域・指導方針など

私の専門は社会学、とくに社会階層論です。社会的不平等と関連するトピックについては専門的なアドバイスができると思います。私の研究してきた具体的なトピックとしては、世代間・世代内社会移動、教育機会の不平等、学歴の社会的経済的リターン、男女間賃金格差、結婚や出産とキャリア形成、未婚化・晩婚化あるいは少子化、性別職域分離、労働市場（スキル・タスク）の二極化、正規・非正規雇用間格差、などがあります。

家族社会学（家族人口学）、労働社会学、教育社会学といった隣接分野についてもある程度はアドバイスできると思います。

研究領域に加えて研究方法についても述べておきます。私がふだん使う研究方法は社会調査データの計量分析（統計）です。とくに計量分析を用いた実証研究をしたいという関心を持つ方には専門的なアドバイスができると思います。

計量分析で研究をされる場合には、少なくとも修士課程の間は、既存社会調査データの二次分析（またはすでに存在する集計データなどの公開データを収集してデータを構築する）で研究されることを強くおすすめしています。どのような質問紙や変数であればちゃんと分析ができるのかということがわからないと、調査設計は到底できないからです。また、修士課程では研究予算がないため自らアンケート調査を企画するとしても有意抽出（無作為抽出ではない）の調査しかできません。有意抽出ではないからだめということはないですが、相当の理論的貢献がなくてはならず、一般的に修士課程の段階でそこまで到達するのは難しいと思います。

実証研究という意味では、インタビューや参与観察、歴史資料などによるデータの収集あるいは分析ならばある程度は理解できますが、自分自身あまり経験がないので、ごくふつうのアドバイスしかできないと思います。理論研究、学説史、制度研究、思想史、哲学、倫理などについてはまったくの専門外で、ほとんど有益なアドバイスはできないと思います。

### 指導教員に関する注意点

学習院大学大学院政治学研究科の修士課程では集団指導が前提であり、希望する指導教員の指導を必ず受けられるとは限りません。進学にあたり指導教員の希望をとりますが、仮に私の研究指導を受けたいと希望していたとしても、研究関心などを総合的に勘案して、私ではない指導教員に付くことになる可能性があります。

私が別の大学などへ異動する、サバティカル（研究休暇）を取得する、といった理由により指導教員となれない可能性がないとはいえません。私がいない or 異動した後も同じように指導ができる教員がいるとは限らないというリスクがあることは認識しておくとよいです。

以上の点を含め、研究指導を受けたいと希望する方は、一度私に連絡をしてマッチングなどを確認されるのがよいと思います。私の連絡先は[Home](index.html)に記載しています。

### 政治学研究科への進学にあたっての留意点

学習院大学の政治学研究科は、その名前のとおり、「政治学」研究科です。そのため、政治学および関連領域の教員が多く在籍する一方で、社会学を専門とする教員は私含めて2名しかいません。授業内容は必然的に政治学に関するものが多くなり、社会学に関する授業はほとんどありません。社会学的な観点からフィードバックを得る機会も多くないでしょう。また学生数も多く専門が分かれているので、同じような立場の大学院の学生と社会学に関する議論を深めるといった機会は限られると思います。もちろん私自身は積極的にアドバイスしますが、以上の点はとくに大学等での研究職を志望する場合、無視できない欠点となるかもしれません。

ですので、社会学に関心があるという場合には、まず最初に、社会学研究科などを有する他の大学院の受験を検討することを強くお勧めします。どうしても私の研究指導を受けたいと希望していたとしても、上述のとおり指導教員を選ぶことができない点には注意が必要です。

以上を踏まえていただいたうえで、以下ではもう少しくわしい内容について記します。

## 大学院（修士課程）進学希望の学生へ

### 大学院進学の条件

学習院大学政治学研究科に進学するためには、9月に実施される一般入試（A日程）または2月に実施される一般入試（B日程）を受験し、合格する必要があります。試験日程や出願の詳細は[学習院大学のAdmissionのページ](https://www.univ.gakushuin.ac.jp/admissions/)から確認してください。

試験は筆記試験と面接試験からなり、筆記試験は「総合問題」および「専門科目」の2種類です。専門科目は分野を選択することができます。「社会学」を選択されるとよいでしょう。

学習院大学法学部政治学科の学生の場合、学部の成績が優秀であれば筆記試験が免除され、面接試験のみで選考される資格を得ることができます。4年生のはじめ頃に通知が行くかと思います。

またFTコースに所属している場合も一定の条件を満たせば試験なしで大学院に進学することができます。詳細は、FTコース担当の先生に確認してください。

「社会学」の専門科目では社会学の基礎的な知識と、社会学的な視点から現象を見ることができるかといったことが問われます。日本語で読めるものとしてはたとえば以下のような教科書を使って勉強すると良いでしょう（リストは随時更新します）。また自分の関心に近い分野についてはさらに教科書や専門書、重要な論文を読み込んでおく必要があります。

-   社会学一般：李侖姫・渡辺深，2022，『入門社会学』ミネルヴァ書房．（過度にテクニカル過ぎずわかりやすいです）

-   社会学一般：盛山和夫・金明秀・佐藤哲彦・難波功士編，2017，『社会学入門』ミネルヴァ書房．（上記よりもより具体的な先行研究などに触れていますが、章の著者によって書き方に癖があります）

-   社会学一般：van Tubergen, Frank. 2020. *Introduction to Sociology.* Routledge.（3年生向け授業のテキストとして使用しています）

-   計量社会学：数理社会学会監修，2015，『計量社会学入門：社会をデータで読む』世界思想社．（階層、労働、家族、教育などのトピックが扱われています）

-   社会階層論：平沢和司，2021，『格差の社会学入門：学歴と階層から考える』北海道大学出版会．（ジェンダーが扱われていないので他の本などで補う必要があります）

-   労働研究：川口大司編，2017，『日本の労働市場：経済学者の視点』有斐閣．（経済学を念頭に置いた書籍ですが実直に先行研究をまとめておりとても良い本です）

-   家族社会学：岩間暁子・大和礼子・田間泰子，2022，『問いからはじめる家族社会学：多様化する家族の包摂に向けて［改訂版］』有斐閣．

-   教育社会学：苅谷剛彦・濱名陽子・木村涼子・酒井朗，2023，『新・教育の社会学: 〈常識〉の問い方，見直し方』有斐閣．

### 身につけておいたほうがよいスキル・経験

私のところで研究指導を受けることを希望しているのであれば、大学院進学までに以下のようなスキルを身につけておくことをおすすめします。これらを備えていればいるほど、大学院進学以降の研究をスムーズに進めることができる見込みは高くなります。

-   基礎的な統計に関する知識（重回帰分析くらいまで）

-   実際にデータを分析した経験

-   研究計画の作成スキル（先行研究で何が問題とされているのか、リサーチ・クエスチョンは何か、なぜそれを明らかにすべきなのか、クエスチョンに答えるためにどのような調査やデータ分析を行うのか、といったことを提示できること）

-   まとまった実証研究論文（日本語なら12000〜20000字程度、英語なら5000〜7000words程度）を書いた経験

-   ゆっくりならば英語論文を読める程度の英語リーディングのスキル

学習院大学法学部政治学科の学生であれば、私が学部で開講している「社会学演習」（ゼミ）をまじめに受講すればこのうち1つめから4つめのスキルおよび経験を得ることができます。

### 修士課程受け入れ後の指導方針

必修授業や特定課題研究については、研究科の説明をよく聞き、間違いのないよう履修してください。

そのほかには基本的にご自身の関心に即して授業を履修してください。私の担当する大学院の授業は履修することを強くおすすめします。

大学院では自ら研究を進めていただくことが中心となりますが、定期的に面談の機会を設け、各学期に提出する特定課題研究を完成させるためのアドバイスをします。私からテーマや課題を与えることはしませんが、テーマが固まっていない人にはテーマを絞っていくための手がかりや先行研究を提示したり、逆にテーマが固まっている人には、そのテーマの意義を明確にするためのより広い文脈を提示するなど、問題設定や意義を明確にするための手助けをします。

修士課程での過ごし方はおおむね次のようになるかと思います。ただし、学生さん自身のこれまでの蓄積などを踏まえて少し変更が生じる場合もあります。

- 修士課程1年目の前半には、先行研究を数多く読んで何がわかっていて何がわかっていないのかを整理し、自身の研究テーマを定めます。また合わせて、計量分析のための基礎的な方法を学びます。

- 修士課程1年目の後半・修士課程2年目の前半には、立てた問いと仮説にもとづいて実際にデータを分析し、それぞれ1本ずつ論文を執筆します。

- 修士課程2年目の後半にはこれまで執筆した論文を合わせ、新たな分析や議論の精緻化を行い、特定課題研究（または修士論文）をまとめます。

### 大学院（修士課程）を修了することの利点と欠点

一般的にいって大学院（修士課程）を修了すること、あるいは修士課程を過ごすことには利点と欠点があります。

利点は第1に、学部では身につけることのできない専門性と、現象に対する分析的な視点、および分析のためのスキルを身につけることができます。社会が複雑化し専門分化が進むなかにあって、こうしたスキルは仮に研究職に就かないとしても、その重要性はますます高まっていると思います。

第2に、研究の楽しさと奥深さを大学院ではなお一層体感することができます。学部段階では必ずしもこうした楽しさを十分に享受することはできないかもしれません。さまざまな知識を得た上で、自分でまだ誰も知らない新しいことを明らかにするというのは（ときにはたいへんですが）とても楽しいことです。

欠点は第1に、お金がかかります。授業料の支払いはもちろんのこと、もしこの期間にフルタイムで働いていたとしたら得られたであろう収入も得ることができません。

第2に、日本で就職する場合、修士課程を修了したからといって必ずしも就職が有利になるといったことはありません。もちろん、修士課程での研究を評価する業界や企業はたくさんあるでしょう。しかし、全体として日本においては、未だ修士課程を修了することによる金銭的なメリットは大きくない可能性があります。とはいえ、修士課程が不利に働くということもないと聞き及んでいます（以上を検証するに足るデータはまだありません）。なお日本を除く他の多くの国では修士号は一定程度評価されるでしょう。

最終的にはこうした利点と欠点を鑑みて、ご自身で納得のいく判断をするのがよいと思います。

### 博士課程への進学について

博士課程（博士後期課程）に進学するとなると、多くの場合は大学などでの研究職を志望するということになるかと思います。研究職に就くことには、望むと望まざるとにかかわらず、少なからず競争の側面があり、たんに研究をしたいという熱意だけで就けるものではありません。そこで、どこの大学院を選ぶかという点も含めて遅くとも修士課程の段階から戦略的に動く必要があります。この点については[立命館大学の高松先生のウェブページ](https://sites.google.com/site/rietakamatsu/%E7%A0%94%E7%A9%B6%E8%81%B7%E5%BF%97%E6%9C%9B%E8%80%85%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%AD%E3%83%BC%E3%83%89%E3%83%9E%E3%83%83%E3%83%97)や[一橋大学の田中先生のウェブページ](https://www.soc.hit-u.ac.jp/~takujit/graduate_school.html)、あるいは[『文系研究者になる：「研究する人生」を歩むためのガイドブック』](https://www.amazon.co.jp/dp/4327379077/ref=cm_sw_em_r_mt_dp_V93ZE547SE0YMS9S465Z)が参考になりますのでチェックしてください。

## 研究生希望の学生へ

### 研究生制度について

日本国外の大学を卒業した方で、日本の大学院への進学を考える場合には、すぐに大学院の入学試験を受けるのではなく研究生制度を利用して（最低でも）1年間は学部で基礎的な勉強をして入学試験の準備をすることをおすすめします。学習院大学政治学研究科においても同様の方針を勧めている教員が多いだろうと認識しています。

研究生の出願期間は毎年1月と3月に設けられています。在留資格などの関係から、余裕を持って書類等の準備をされることをおすすめします。詳しくは[学習院大学のAdmissionのページ](https://www.univ.gakushuin.ac.jp/admissions/)を参照してください。

研究生になったとしても大学院に自動的に進学できるわけではなく、大学院入試を受験しなければなりません。また、本学の研究生を経験したことによって有利に扱われるということもありません。くれぐれも注意してください。大学院受験に際しての注意点は上記「大学院（修士課程）入学希望の学生へ」を参照してください。

### 研究生受け入れの条件

政治学科では日本語能力試験（JLPT）でN2以上の成績を取得している必要があります。N1以上の成績を有していればなおよいです。日本ではほとんどの場所で日本語のコミュニケーションを取ることが求められるので、日本語はできるに越したことはないです。とはいえ、もちろん重要なのは語学力よりも研究能力です。

コミュニケーションを取る際には日本語のほかに英語でもよいですが、私自身はあまり英語がうまいわけではないのでご承知おきください。

私を指導教員としたい場合には、本学政治学研究科の利点と欠点をあらかじめ把握したうえで、あらかじめ履歴書と研究計画書を送っていただき、面談希望を申し出てください。研究計画書などを拝見して、問題関心やこれまでの勉強内容などをお伺いして、最終的に私が研究指導できる範囲であると判断すれば、受け入れを内諾します。ただし、内諾したとしても、教授会を経て受入れが認められない可能性がないとは言い切れません。選考結果が出るのを待ってください。

### 研究生受け入れ後の指導方針

基本的にはご自身の関心に即した授業を取っていただき、ご自身で勉強を進めていただくというふうになります。個別相談の希望があれば適宜応じます。

私が担当する「社会学III」「社会学IV」と「社会学演習」は必ず履修してください。また、政治学科で開講される「社会統計学I」「社会統計学II」はぜひ履修してください。

私の担当する授業のうち「政治学科基礎演習I」「政治学科基礎演習II」は1年生用の授業なので、履修はできません。

そのほかには、たとえば以下のような科目の履修を検討してもよいかもしれません（他の学部学科の授業を履修できるのかはわかりませんので、事務の方に確認してください）。

-   法学部政治学科「社会学I」「社会学II」

-   法学部政治学科「社会心理学I」「社会心理学II」

-   法学部政治学科「社会政策論I」「社会政策論II」

ただし、ご自身の勉強もあると思いますので、多くとも週4--5コマくらいに抑えるのがよいと思います。
