---
title: "Japan-Hong Kong Early-to-Mid Career Sociologists' Study Group"
author: "Ryota Mugiyama"
date: "2026-09-02"
---

## Purpose

Provide critical but encouraging feedback to our colleagues’ ongoing studies and advance the projects, with the ultimate goal of having our research accepted for publication in a global journal outlet.

## How it works

Assign one or two speakers per each meeting. Each session will be 50 minutes in total, including presentation and discussion.

Speaker(s) share any stages of their research. The example is as follows:

- **Early-stage brainstorming**. The speaker talks about their own initial ideas, proposals, or preliminary results and discusses the idea with the other participants.
- **Seminar-style talk**. The speaker presents their own research like seminar talks. Then other participants provide comments, suggestions, or any feedback for future potential directions.
- **Peer pre-review of manuscript**. The speaker shares their ongoing manuscript in advance and presents the manuscript. Then other participants provide feedback to improve the manuscript in terms of framing, theory, literature review, or analyses.
- **Handling journal reviews**. The speaker shares their submitted paper and the reviewers’ comments they received. The other participants offer advice or suggestions on how to address the reviewer’s comments.

Then determine the schedule and speakers for upcoming meeting at the end of meeting (if possible).

## The way of contact

Email

## Meeting platform

Zoom
