---
title: "不平等研究に関する輪読会 Reading circle of inequality studies"
author: "Ryota Mugiyama"
date: "2025-01-14"
---

## 研究会趣旨

### 目的

英文トップジャーナルに最近掲載された論文の内容を紹介し、研究のトレンドを掴んたりアイデアを得たりする。

### 対象ジャーナルの例

**General**

- American Sociological Review
- American Journal of Sociology
- Social Forces
- European Sociological Review
- Sociological Science
- Social Science Research

**Subfield**

- Demography
- Population and Development Review
- Sociology of Education
- Journal of Marriage and Family
- Gender & Society
- Socio-Economic Review
- Research in Social Stratification and Mobility

そのほか、Administrative Science Quarterly, Criminology, Social Science & Medicine, Social Networks, Nature Human Behavior, Proceedings of the National Academy of Sciences (PNAS) など

**Method**

- Sociological Methods and Research
- Sociological Methodology

### 進め方

1. 報告担当者は各自、会合までに自分の読みたい論文をspreadsheetに書き込み、googledriveにアップロードする。テーマは広い意味で不平等にかかわるものとする。
2. 会合では、報告者が15分程度でその論文の内容を紹介する。報告者はレジュメやスライドを準備してもいいし、しなくてもいい。他の参加者は、当該論文を読んできてもいいし、読まなくてもいい。
3. 内容紹介を受けて、議論する。内容の細かな「批判的読解」よりも、当該の研究がどのような位置づけで、何を明らかにしていて、何が新しいのか、理論や枠組みの応用・発展可能性についてざっくばらんに話すのを主眼とする。
4. 各回の報告者数はとくに定めない。時間は1人につき40分（15分以内報告 + 25分議論）くらいを目安とする。

### 開催頻度

一回につき2人程度が話題提供で、3〜4週間に1回程度。

### 参加者

随時募集中で、職位などは問いません。社会学分野における不平等に関する研究に関心がある方ならどなたでも。
