---
title: "感想メモ：Sociology as a Population Science by John H. Goldthorpe (2015)"
author: "Ryota Mugiyama"
date: "2017-06-12"
categories: "研究実践"
---

[表題の本](https://doi.org/10.1017/CBO9781316412565)を最近読みました。面白かったので簡単な要約（もれなく要約したわけではなく、自分の関心に即して要約しています）を混じえた感想メモを残しておきます。

本書は、著者のGoldthorpeが（目指すべき）社会学観を提示するというものです。

Goldthorpeは、タイトルのとおり社会学はpopulation scienceとして理解されるべきと主張します。populationの部分が研究の対象を、scienceの部分が研究の方法をそれぞれ指していると考えてよいです。populationは日本語にするのが難しいですが……集団、とか、人びと、とかですかね。ひとまず以下では、「集団」という訳を採用しておきます。

## 規則性を明らかにし、それを説明する (chapter 1)

populationは人間だったり動物だったり、あるいは分子など、何らかの個体の集まりを指すわけですが、その重要な性質は、各個体の状態だったり行動だったりが決定論的ではなく、確率的だということにあります。その結果として、個体の集まりには何らかの確率的な規則性（regularity）が現れてきます。

社会学の関心となる規則性は、時間的あるいは空間的な広がりのなかでの、人間の集団、およびその下位集団ごとの規則性にあります。たとえば、「アメリカの労働者は日本の労働者とくらべて多く転職する」とか、「女性は男性と比べて所得が低い」とか、「先進諸国の多くで離婚率は上昇傾向にある」とかいったものが規則性の例として挙げられると思います。

population scienceたる社会学の目的は、**こうした規則性を見えるようにして（visible）、そしてそれを説明する（transparent）**ことにあるといいます。規則性の説明にあたっては、個人の行動あるいは行為によって説明されなければならないと述べられています[^1]。

[^1]: 行動（behavior）と行為（action）の違いは、行動がどちらかというと意図を介さない自動的な反応を指すのに対して、行為は個人の意図をともなう、という含みがあるという点だと理解しています。

## 規則性を個人の行為によって説明する (chapter 2--3)

個人の行為を介して規則性を説明する、という図式は、そう**でない**説明と対比すると分かりやすいと思います。Goldthorpeは自身の立場を、個人主義的パラダイム（individualistic paradigm）と呼び、全体主義的パラダイム（holistic paradigm）と区別します。

全体主義的パラダイムにおいては、個人は規範を内面化し、あらゆる個人がそれにしたがって（半ば自動的に）行動すると想定されます。機能主義などに代表されるように、ここでは集団の規則性は、集団レベルの力学によってのみ説明されます。Goldthorpeは引用していませんが、Granovetterの言うところの「過剰社会化（over-socialized）」された個人、という見方です[^2]。

[^2]: Granovetter, Mark. 1985. "Economic Action and Social Stracture: The Problem of Embeddedness." *American Journal of Sociology* 91(3):481--510.

一方でGoldthorpeの寄って立つ個人主義的パラダイムでは、知識をもったうえで選択する（informed choice）、という個人の自律性を強調する見方をとります。**個人の行為にはたらく規範や構造による制約を認めたうえで、個人の行為によって集団レベルの規則性を説明する**、というのがGoldthorpeの提示する説明のルートです。

## 説明すべきは集団の規則性であり、単一のイベントではない (chapter 4)

Goldthorpeは、社会学における説明の対象はあくまで集団の規則性であることを強調します。その対比として単一のイベント（singular event）が挙げられます。たとえば、「フランス革命はなぜ起こったか？」といった問いは、population scienceとしての社会学における説明の対象とはなりません。なぜなら、そこには規則性がないからです。

「フランス革命はなぜ起こったか？」という問い自体は無意味なものではないですが、これを明らかにすることは歴史学（など）の役割であり、社会（科）学が問うべきは、「なぜ（いかなる条件のもとで）革命が起こるのか？」という問いになります。つまりここではフランス革命は数ある革命のうちの1つの事例であって、事例を超えた理論的な基礎に基づいた説明を探求すべきである、ということになります。このような考え方は、社会科学の標準的な考え方と同一であると思います[^3]。

[^3]: G.キング・R.O.コヘイン・S.ヴァーバ著，真渕勝監訳，1994（2004），『社会科学のリサーチデザイン——定性的研究における科学的推論』 勁草書房．

ここは科学としての社会学を志向するGoldthorpeの考え方が強く現れているところで、こういう志向に反感を持つ人もいると思われます。

これは普段から思っていることですが、こうした志向に共感できるかどうかは、扱っている対象のpopulation（ここでは「母集団」、といってもいいと思います）をどの程度想定できるかに依存するのかもしれません。個人を対象とするサーベイ調査を行っている人からみれば、規則性を説明対象とする志向には違和感は少ないと思います。一方で、「社会運動」「都市」「コミュニティ」などといった中間集団を対象とするような研究は、なにがpopulationであるのかが明確には見えにくいと思います。さらに調査の方法も丹念な聞き取りなどを中心とする事例調査となり、事例の個別性がクローズアップされやすくなります[^4]。

[^4]: あるいは、そもそもpopulationがない（けれど、問うべき価値のある）対象があるかもしれません。

## 統計学とサーベイ調査の有用性 (chapter 6--7)

社会学の説明対象たる集団の規則性を取り出すうえで、サーベイ調査およびその統計学的分析は主要な方法となります。代表的なものとしては、成人を対象とするサーベイ調査を使って、親の職業と子の職業のクロス表をつくり、親子間の職業移動パターンを明らかにすることなどが挙げられます。

ここで、次の説明のステップに進むために重要なことは、**第1に説明されるべき規則性が十分に認められるか、第2にその規則性が擬似関係でないかを確認する**ことです[^5]。

[^5]: Goldthorpeは明確に擬似関係という言い回しをしていないですが（p.87）、Lazarsfeldのエラボレーションなどの話を出しており、おそらくそうしたことを含意しているのではないかと思います。

第1は、たとえば統計的に有意であるとか、そうした研究結果が複数報告されているか、といった基準で判定することができると思います。第2は、他の関連しうる変数を統制してもなお変数間の関連が残るか、あるいはその変数間の関連が理論的に理解できるか、といったところで判定することができると思います。Goldthorpeはどの程度の結果が得られれば説明されるべき規則性が認められたと言ってよいのかを明確に書いているわけではないですが、完璧に規則性の存在を確証できることはないので、研究目的に応じて決めるべきだろうと思います。

## 統計の限界：因果的説明 (chapter 8)

統計を使った分析は、社会学にとって説明すべき対象である集団の規則性を明らかにするうえで非常に強力なツールですが、それ自体はその規則性の因果的説明とはなり得ません。

変数主義的社会学（variable sociology）では、従属変数の分散の分解がそのまま説明となります。たとえば、「所得の分散が教育によって説明される」とか、「所得と性別の関連が教育によって説明される」とかいう言明がこれにあたります。このような説明は、その背後でどのような社会的プロセスが働いているのかを全く考えることなく成り立ちます。

Goldthorpeは（多くの社会科学者はそうだと思いますが）こうしたタイプの言明を説明とは認めません。個人主義的パラダイムに立つ社会学者は、規則性が生み出されるプロセスを、個人の行為と相互行為から理解すべきであると主張します。言い換えれば因果関係の同定は、統計的な手続きのみではなく、（そうした結果を生み出す）主体の行為あるいは相互行為を組み込んだ理論が必要になるということです。

そして重要なのは、chapter 4で述べたとおり、ここでの行為は、**個人の行為にはたらく規範や構造による制約を認めたうえで**行われる合理的な行為である、という点です。

## メカニズムにもとづく因果的説明 (chapter 9)

Goldthorpeが規則性の説明として重要視するのは、メカニズムにもとづく因果的説明です。メカニズムは、以下の2つの条件を満たしている必要があります。第1に、因果的十分性です。すなわち、個人がいかに行為・相互行為をしているかを通して、規則性が生成されまた維持されるかどうかが説明できる、ということを意味します。第2に、そのメカニズムが実際に働いているかどうかが経験的な検証に開かれていることです。

では、どのようにすればメカニズムが実際に働いているのかを同定できるのか？Goldthorpeは3つの研究戦略を挙げています。第1に、直接観察です。これは例えば聞き取り調査などによって、なぜそのような選択・行為をしたのかを尋ねたりするといった方法が挙げられます。第2に、因果メカニズムに関する仮説から導かれる観察可能な含意を、統計分析によって検証し、間接的に因果メカニズムの存在を傍証することです。第3に、実験によって処置をコントロールすることです。この3つは補完的なものであり、あるメカニズムが作動しているかどうかは、多くの方法によって検証されるべきだと述べられています。

## まとめと感想

Goldthorpeの主張をまとめれば、「population scienceたる社会学の目的は、**集団の規則性を見えるようにし、それを説明する**こと、そしてその説明は、**個人の行為にはたらく規範や構造による制約を認めたうえで、個人の行為および相互行為に求めるべきである**」というふうになると思います。

集団の規則性を見えるようにする、というのが初めにくるあたりが社会学らしさを表しているように思います。つまり、社会学の初発の関心はあくまでも「社会がどのようであるのか」にあるということです[^6]。

[^6]: これに関連して、社会学の理論にはしばしば、それは説明ではなく記述なのでは？（例：Beckの「個人化」など）というようなものがありますが、このような記述と説明の混乱が起こるのも、こうした社会学の関心に由来している部分があるのかもしれません。

本書自体は、普段統計的な手法を使って研究している社会学者の（なかば無意識的な）研究のプロセスを捉えたもので、すごく新しいというわけではないと思いますが、自分の研究が今どのような地点にあって、そこから何が言えるか、次に何をすべきかを示してくれるような、指針の1つになる文章だと思います。

