---
title: "おすすめの計量分析の教科書（社会学向け）"
author: "Ryota Mugiyama"
date: "2018-02-18"
categories: "計量分析"
---

## **はじめに**

自分の所属している大学院では基本的に研究方法については独学で身につけることが期待されています。なので、これまでに自分でいろいろと教科書を調べて読みました。もしかしたら同じようにどのような教科書を読むべきか悩んでいる人がいるかもしれないので、何かの役に立つことを期待して、自分が読んでみて良いと思ったテキストを挙げておきます。

挙げているテキストはすべて英語です。もちろん日本語で書かれたテキストにもいいものはたくさんあるのですが、英語のテキストは基本的に日本語のテキストよりも長い分量で丁寧に書かれているので、独学には適していると思うからです。

社会調査法などをとおして基本的な方法（度数分布、平均・分散などの要約統計量、クロス集計、平均値の比較、相関係数などの2変量の分析、統計的推測、仮説検定など）をすでに学習した、社会学系の大学院生を想定しています。もしこれらをまだ勉強していないという場合には、先にこちらを勉強しておくほうがいいと思います。

## **計量分析の基礎**

計量分析の基本はOLS回帰分析なので、まずは計量経済学の基礎的なテキストから入るのが一番良いと思います。

### [Introductory Econometrics: A Modern Approach](https://www.amazon.co.jp/dp/1337558869)

分厚いので時間がかかると思いますが、これ一冊きちんと読めていれば回帰分析に関しては他にテキストはいらないのではないかと思います。

ふつうのクロスセクションのOLS回帰分析のほか、時系列分析、パネルデータ分析、操作変数法、同時方程式、制限従属変数、カテゴリカルデータ分析、サンプル・セレクションモデルなどが扱われていますが、割かれている紙幅はさほど多くないので、このあたりは他のテキストを使うほうがいいと思います。

ただし、数式慣れしていない場合は、これでも少し難しいと感じるかもしれません。そういう場合は、以下の教科書を読んでから本書にチャレンジするといいかもしれません。

### [Regression Analysis for the Social Sciences](https://www.amazon.co.jp/dp/0415991544)

米国留学中の友人から教えてもらった本で、実際の論文例や統計ソフトの出力結果などが豊富に載っており、実際にどのようなことをするのか、イメージがわきやすいつくりになっています。計量分析の経験が少ないとか、数式が苦手だという人はこれを読んでからWooldridgeに進むとよいと思います。

社会学の場合は、連続変数よりもカテゴリカル変数を扱うことのほうが多いです。もちろんOLSによる回帰分析が多変量解析の基本なので、これはきちんと押さえたうえで、別途カテゴリカル変数を用いるモデルについても勉強する必要があります。

## カテゴリカル・データの分析

### [Regression Models for Categorical and Limited Dependent Variables](https://www.amazon.co.jp/dp/0803973748)

自分が読んだので一番良かったのはこれです。ロジットモデル、プロビットモデル、順序ロジットモデル、多項ロジットモデル、条件つきロジットモデル、Type-1, Type-2トービット・モデル、ポアソン回帰・負の二項回帰モデルが扱われています。

### [Regression Models for Categorical Dependent Variables Using Stata](https://www.amazon.co.jp/dp/1597181110)

Stataを使う人であれば、この本も評判がいいです。前述の本は出版が1997年と若干古いので、こちらのほうがより新しいです。とくに結果の解釈のしかたについて、Marginal effectの算出なども含めてかなり紙幅を割いているので、読んでおくとより説得的な議論ができるかもしれません。

## 生存分析／イベントヒストリー分析

[こちらの記事](https://ryotamugiyama.com/2016/01/08/text_eventhistory/)をご覧ください。

## 階層線形モデル／マルチレベルモデル

マルチレベル・モデルはざっくり言ってしまえば、

1. 個人のなかに複数の観察時点が入れ子になっている、いわゆる縦断データの分析＝同一個人のなかの複数時点における観察値どうしが相関する。
2. 学校、職業、地域、国などのより大きな単位のなかに個人が入れ子になっている＝大きな単位を共有する個人の観察値どうしが相関する。

の2つの場面で用いられます。いずれも基本的なモデリングに関しては特徴を共有していますが、細かいところでは違いがあるので、自分がどのような分析をやりたいのかによって読むテキストを変えたほうがいいと思います。

### [Applied Longitudinal Data Analysis: Modeling Change and Event Occurrence](https://www.amazon.co.jp/dp/0195152964)

時間による値の変化を捉えるための2つのモデル（成長曲線モデリングと、イベントヒストリー分析）を扱っています。前半が成長曲線モデリング、後半がイベントヒストリー分析です。以下の日本語訳もでています。

日本語訳書籍（[前半の成長曲線モデリングのみ訳出したもの](http://www.asakura.co.jp/books/isbn/978-4-254-12191-9/)、[後半のイベントヒストリー分析のみ訳出したもの](https://www.asakura.co.jp/books/isbn/978-4-254-12192-6/)）もあります。

### [Multilevel and Longitudinal Modeling Using Stata, Fourth Edition](https://www.amazon.co.jp/dp/1597181366)

Stataを使うのであればこの教科書がほとんどすべての方法を網羅しています。

### [Hierarchical Linear Models: Applications and Data Analysis Methods](https://www.amazon.co.jp/dp/076191904X)

先に挙げた2.の場面を想定したマルチレベル・モデルであれば、このRaudenbush and Brykの本はとても評判がよいと思います。第2版が2002年なので少し古いというところもありますが、なぜ中心化をするのかとか、どういうときに切片にランダム項を入れるのか、あるいは傾きにランダム項を入れるのか、どのように解釈をするべきかといった細かいところまで扱っていておすすめです。

### [Applied Panel Data Analysis for Economic and Social Surveys](https://www.amazon.co.jp/dp/B01HCAV7LQ)

パネルデータの分析を念頭に置いた本です。データの作り方から記述的な分析、固定効果モデル、ランダム効果モデル、一階差分モデル、イベントヒストリー分析までカバーしており、オーソドックスではありますが非常に分かりやすく説明されています。Stataのコードもあります。

## その他

その他、バラバラと思いつくものを挙げておきます。興味関心に応じて参考にしていただければと思います。

### [Counterfactuals and Causal Inference: Methods and Principles for Social Research](https://www.amazon.co.jp/dp/1107694167)

自分自身は操作変数法、傾向スコア法などの因果推論的な分析を行ったことはないので、あくまでも論文を読むうえで押さえておいたほうがいいだろうという程度の距離感で因果推論と付き合って（？）います。

この本はデータ分析のhow to的な教科書ではありませんが、社会学者の書いた因果推論本であるということで、社会学を専攻している人にとっては読みやすいと思います。この本を読んで因果推論をするというよりはむしろ、モデルを組み立てるにあたってどのようなことを気をつければよいか、ということを学ぶという感じになるのではないかと思います。

### [Mostly Harmless Econometrics: An Empiricist's Companion](https://www.amazon.co.jp/dp/0691120358)

同じく因果推論ものとしてもう一冊。今は計量分析の方法についても、理想的な因果効果を測定できる実験からの差分で考えることが多くなっていて、本書はその火付け役に位置する教科書と認識しています。日本語訳も出ていますが、どちらでも好きな方を選べばよいと思います。

### [Flexible Imputation of Missing Data](https://www.amazon.co.jp/dp/1032178639)

欠損値を補正する方法として現在主流な方法である多重代入法についてのテキストです。自分でも一応論文（報告書）で使用したこともあるのですが、まだなんとなく手探りの状態です。アメリカなんかでは、社会学でもImputationはやって当たり前というふうになっているようです。

Rのコードがたくさん乗っているので、手を動かしながら勉強することができます。Stataでのやり方については[Stata multiple imputation]とかで検索するといい感じのウェブサイトにたどり着けると思います。

### 要因分解

2つの集団で回帰分析を推定して、2つの集団における変数の分布の違いがどの程度両者の間の従属変数の差を説明するのかを検討する、というのが要因分解法です。社会学でもときどき使われます。これは教科書は見当たらないのですが、いわゆるBlinder-Oaxaca decompositionにかんしては以下の論文がわかりやすくまとめていると思います。

Jann, Ben. 2008. "The Blinder-Oaxaca Decomposition for Linear Regression Models." *Stata Journal* 8(4):453–79.
もう少し発展的な方法まで扱っている論文は以下になります。

Fortin, Nicole, Thomas Lemieux, and Sergio Firpo. 2011. "Decomposition Methods in Economics." Pp. 1–102 in *Handbook of Labor Economics*, vol. 4. Elsevier Inc.

この論文はChapter 1–Chapter 7まであるのですが、正直数式がたくさんあって難しいので、Blinder-Oaxaca decompositionだけ知りたいのならChapter 1と3だけ読むといいと思います。より発展的な方法についてはChapter 4以降に書かれています。

### [Quantile Regression](https://www.amazon.co.jp/dp/B00KTPM1CQ)
経済学ではよく使われる分位点回帰分析ですが、最近は社会学でも使われることが増えてきたように思います。とりわけ社会的・経済的な格差を問題にするときには通常の（平均への）回帰分析だけでなく、分位点回帰分析についても押さえておくと選択肢が広がります。この本はSageの緑本ですが、分かりやすくまとまっており、おすすめです。

## そのほか

ここまで取り上げてこなかった手法としては、因子分析系、対応分析、クラスター分析、共分散構造分析、ネットワーク分析まわり、潜在クラス分析、潜在成長曲線モデル、シークエンス分析、対数乗法連関モデルなどの発展的なログリニア・モデル、質的比較分析（QCA）、時系列分析などがあります。このあたりは自分では使ったことがなかったり、詳しくなかったりするので、紹介することはしません。

