---
title: "初年次ゼミで何をする（した）のか：その2"
author: "Ryota Mugiyama"
date: "2021-12-28"
categories: "授業関連"
---

今学期も先学期に引き続き、基礎演習という、おおむね初年次教育に該当する内容を扱う必修科目を担当した。しかし、自分はあまりまともな初年次教育なるものを受けた記憶がなく（きっとまじめに授業を受けていなかったのだろう）、いざやってくださいと言われてなかなか困ってしまった。そこで、どのようなことをやったのか、およびそれらがどの程度うまくいった（いかなかった）のかについて記しておくことで、今後の自分、および似たような状況にあるかもしれない人のために、タイトルのとおり、初年次ゼミでやったことについてのメモを残しておくことにする。

以前に書いた記事の続きだと思って見てください。

## 前提

法学部政治学科の1年生が受ける基礎演習という授業が後期にもあり、それでどのようなことを行ったのかをメモとして記しておく。位置づけはいわゆる初年次教育と考えるとよいと思う。

後期は前期とは異なり、学生は自身の興味にもとづいて教員を選ぶことができる。教員は事前に授業でどのようなことを扱うかをアナウンスする。なので、ランダムに割り振られるよりは教員の関心に近い学生が授業を受けている可能性が高い。

## 内容

授業では以下のようなことを行った。

-   Excelを使った簡単な演習

-   文献購読（レジュメの作り方、議論の仕方）

-   論文購読（レジュメの作り方、議論の仕方）

-   個人研究報告（スライドを使った期末レポート構想の報告）

以下それぞれの内容について詳述する。

### Excelを使った簡単な演習

統計センターが提供している[SSDSE](https://www.nstac.go.jp/SSDSE/ "https://www.nstac.go.jp/SSDSE/")（教育用標準データセット）から取得した都道府県別データを用いて、棒グラフを作ったり、折れ線グラフを作ったり、平均値を計算したり、散布図を描いたりした。あらかじめ手順を一つひとつ文章にしてLMS上に記載し、それに沿ってゆっくりやっていくと、おおむねみんなできているようであった。学生のExcelのスキル（もっというとパソコンのスキル）の分散は大きいため、新規フォルダを作成する、ファイルをダウンロードする、作成したフォルダにダウンロードしたファイルを移す、ダウンロードしたファイルを開く、といったことも一つずつやっていく必要がある。Ctrl + CやCtrl + Vなどのショートカットキーも知らない学生のほうが多い印象だった（そもそも自分はいつどこで覚えたのだろうか...？記憶がない）。とはいえ、高校まででこういった基礎的なPC操作を勉強していなければ知らなくても仕方がないだろう。逆にできる学生はLMSの手順をみてさっさと進めていたりしていた。

副読本として畑農鋭矢・水落正明，2017，『データ分析をマスターする12のレッスン』有斐閣．を指定し、1章、2章、3章、5章まで読んでもらった。意外とExcelで基礎的な作図（棒グラフ、折れ線グラフ、散布図くらいまで）や計算などについて扱っており、かつ社会調査などの集計を念頭に置いた書籍がなく（統計的検定などを扱った書籍はたくさんあるのだけど、検定以前の記述的集計のことをもっと知りたい）、選ぶのにかなり苦労した。もしいい本があれば、どなたか教えて下さい。

### 文献購読

以下の2冊を購読した。

永吉希久子，2020，『移民と日本社会：データで読み解く実態と将来像』中公新書．

周燕飛，2019，『貧困専業主婦』新潮社．

永吉（2020）は自分があまり詳しくない分野だったので単純に勉強になった。こちらのほうがやや議論が活発だった印象。やはりまだ移民というのは（日本で生まれて日本で育った学生の多くにとっては）身近な現象ではないものの、様々な場所で触れる機会は増えつつあり、関心はあるもののよく知らない、ということがあるのかもしれない。

### 論文購読

1回につき2本ずつ、以下の8本の論文を購読した。

小笠原祐子，2009，「性別役割分業意識の多元性と父親による仕事と育児の調整」『季刊家計経済研究』81: 34--42.

武石恵美子，2014，「女性の昇進意欲を高める職場の要因」『日本労働研究雑誌』56(7):33--47.

麦山亮太，2017，「職業経歴と結婚への移行：雇用形態・職種・企業規模と地位変化の効果における男女差」『家族社会学研究』29(2):129--41．

宮澤仁・若林芳樹，2019，「保育サービスの需給バランスと政策課題：GISを用いた可視化から考える」『日本労働研究雑誌』 61(6):35--46．

古田和久，2016，「学業的自己概念の形成におけるジェンダーと学校環境の影響」『教育学研究』83(1): 13--25．

秦正樹，2016，「「新しい有権者」における政治関心の形成メカニズム：政治的社会化の再検討を通じて」『選挙研究』32(2):45--55.

岡檀・山内慶太，2012，「自殺希少地域のコミュニティ特性から抽出された「自殺予防因子」の検証：自殺希少地域および自殺多発地域における調査結果の比較から」『日本社会精神医学会雑誌』21(2): 167--180．

三谷はるよ，2019，「社会的孤立に対する子ども期の不利の影響：「不利の累積仮説」の検証」『福祉社会学研究』16: 179--99．

論文選定に際しては、授業への応募の際に学生に書いてもらったレポート（1000字程度）をもとに学生の関心をみて、関係しそうな論文を選ぶことにした。比較的反応が良かったと感じたのは古田（2016）と秦（2016）で、いずれも10代の学生を扱った論文なので、学生自身の経験などに引きつけた議論などができたように感じる。岡・山内（2012）は記述的な研究だが、さまざまな要因に触れており、議論がしやすかったように思う。一方で労働に関係する論文はあまりうまくいかないことが多く、武石（2014）や麦山（2017）は内容に踏み込んだ議論はほとんどなかったように思う。このあたりのトピックは3--4年生向けに行っている授業では反応が変わってくるので、就職活動を経るとそういったトピックへの関心が出てくるのかもしれない。

### 個人研究報告

これについては前期と同じ形式で行った。授業で読んだ論文から関心を持ったという学生もいてくれたのはよかった。

前期と比べると、非行、虐待、孤立、自殺、DVといった貧困や格差と関係の深いテーマに関心をもっている学生が多い印象を受けた。その他には、若年投票率、女性議員割合の低さ、未婚化・晩婚化、介護、男性育休、保育士不足、ダイバーシティ、食品ロスなど。自分の授業の応募レポートのテーマは「現代日本における社会問題」と限定しているため、基本的には日本における社会問題と関係するテーマに関心を持っている学生が多いと思う（つまり、日本以外の政治や社会、国際関係、あるいは哲学や倫理、思想、歴史に関心をもつ学生は別の授業を取っていると思う）。

## 所感

前期よりは学生が喋ってくれることが増えた。たんに後期になって演習形式の授業に慣れてきたからかもしれないし、積極的に発言してくれる人がいたので、他の人も影響を受けて発言してくれるようになったのかもしれない。

Wordの使い方（見出しの設定、脚注の入れ方、改行・改ページ、図表番号、などなど）というのをまとまった時間を取って授業をしたほうが良いのではないかと感じた。他の必修授業などでどれくらいやっているのかわからないが、Wordのシェアはまだまだ揺るがないだろうから、こういったテクニックを知っておくと、今後レポートを書いたりするだけではなく、仕事をするようになってからも役に立つかもしれない。

PowerPointでのスライドの作り方のコツ（ページ数を入れる、フォントの選定、文字が小さくなりすぎないようにする、奇抜なデザインのスライドは選ばないなど）についても、まとまった時間を取っても良いのではないかと感じた。
