---
title: "初年次ゼミで何をする（した）のか"
author: "Ryota Mugiyama"
date: "2021-07-18"
categories: "授業関連"
---

所属が変わって早くも3ヶ月半が経ち、もうすぐ1学期が終わりそうな気配だ。今学期の前半は慣れないことや授業準備、プライベートで忙しくてんてこまいだったけど、7月ころからようやく落ち着いてきた。

今学期担当した授業の1つに、基礎演習という、おおむね初年次教育に該当する内容を扱う必修科目がある。しかし、自分はあまりまともな初年次教育なるものを受けた記憶がなく（きっとまじめに授業を受けていなかったのだろう）、いざやってくださいと言われてなかなか困ってしまった。そこで、どのようなことをやったのか、およびそれらがどの程度うまくいった（いかなかった）のかについて記しておくことで、今後の自分、および似たような状況にあるかもしれない人のために、タイトルのとおり、初年次ゼミでやったことについてのメモを残しておくことにする。

## 前提

-   受講生は1年生である：大学1年生なので、大学で標準とされているような知識についてはまだもっていない。一方で、大学に進学したばかりなので学習意欲は高いのではないかと思われる。実際、報告をサボったりする人はおらず、欠席も少なかった。

-   法学部政治学科の授業である：政治学科を選んでいるくらいので、人文学や自然科学よりは社会科学に興味があると思われる。なので少なくとも、社会の問題について考えたりすることが嫌いなわけではない学生が主だと思われる（実際に一人ひとり尋ねたりしたわけではないけれど）。

-   必修に相当し、受講生はランダムに割り当てられる：なので、必ずしも教員の専門分野である社会学あるいは社会階層研究に関心があるとは限らない。

## 内容

授業では以下のようなことを行った。

-   レポート・論文とは何か、についての説明

-   文献購読（レジュメの作り方、議論の仕方）

-   論文購読（レジュメの作り方、議論の仕方）

-   個人研究報告（スライドを使った期末レポート構想の報告）

以下それぞれの内容について詳述する。

### レポート・論文についての説明

このテキストを使用した：

[河野哲也，2018，『レポート・論文の書き方入門 第4版』慶應義塾大学出版会．](https://www.amazon.co.jp/%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88%E3%83%BB%E8%AB%96%E6%96%87%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9%E5%85%A5%E9%96%80-%E7%AC%AC4%E7%89%88-%E6%B2%B3%E9%87%8E-%E5%93%B2%E4%B9%9F/dp/4766425278)

1--2章、3--4章と分けてそれぞれ事前に読んできてもらい、内容に関する補足を行った。初年次教育用に書かれたテキストであり、レポートあるいは論文について「レポート・論文は、問い -- 答えという問答形式でできていなければなりません」（p.7）と端的に定義している。記述は難解ではなくわかりやすい。一方で、著者は哲学・倫理学専攻のため、社会科学とはすこし勝手が違うところもあるかなというところがないでもなかった。たとえばデータを使った論証などを念頭に置くのであれば、もっと適した書籍があるかもしれない。今後検討の余地がある。

### 文献購読

このテキストを使用した：

Rosling, Hans, Ola Rosling, and Anna Rosling Rönnlund. 2019. Factfulness: Ten reasons we\'re wrong about the world----and why things are better than you think. Sceptre.（[上杉周作・関美和訳，2019，『FACTFULNESS：10の思い込みを乗り越え、データを基に世界を正しく見る習慣』日経BP社．](https://www.amazon.co.jp/dp/B07LG7TG5N/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1)）

一回につき3章ずつ読んでいった。各章1名ずつのレジュメ担当者を置き、それぞれA4で2ページ程度のレジュメを作成してもらったうえで、報告、議論を行った。

この本はとても平易に書いてあるうえ、社会科学を学ぶうえで必要な態度を教えてくれるという意味でとてもいい本だと思う。広く言うとこの本は統計リテラシー系の本にも含まれると思うが、いわゆる統計リテラシー系の書籍はとにかく他人や既存の統計をけなすネガティブなものが多かったりする一方で、どういうふうに考えたらいいのかについては何も語らなかったりするものも多い。こうしたなかで、この本は一貫してポジティブに書かれているところもすばらしい。著者自身の科学者としての態度も優れていて、学ぶことが多い。来年からも使うかもしれない。

担当してくれた学生のレジュメはいずれもよくまとまっていた。著者が述べているような「本能」や傾向などについて、身近に当てはまるようなものはあるかを考えてもらったりするのは、いい練習になるかもしれない。あるいは、[著者らの整備したウェブサイト](https://www.gapminder.org/)を実際に見てみたりするのも、おもしろいかもしれない。

レジュメの作り方については文献購読以前に簡単に解説をした。これは人によって好みがあるところだと思うが、自分は長々と文章を書き連ねた長大なレジュメはあまり好きではないので、原則2ページ以内におさめるように指示した。また、たんに文章を書くのではなく、適宜太字や箇条書きなどをつかって、授業ノートのようにまとめるようにというふうに伝えた。内容の要約のほか、考察やコメントの書き方についても「このようなことを書くんだ」というふうに前もって伝えた。もちろん、担当箇所がどこか、所属や名前、といった基礎的な情報を書くようにも伝えた（というか、それ用のテンプレートとなるwordファイルを事前に配布した）。

### 論文購読

書籍を読むだけでは実際にレポートや論文というのがどのようなものなのかというのはわかりにくいかなと思って、実際に書かれた論文を読むことにした。具体的には、以下の5本の論文を指定した。

[余田翔平，2012，「子ども期の家族構造と教育達成格差」『家族社会学研究』24(1): 60--71．](https://doi.org/10.4234/jjoffamilysociology.24.60)

[吉田航，2020，「国内大企業の新卒採用における学校歴の位置づけ：大学別採用実績データの計量分析から」『教育社会学研究』107: 89--109．](https://researchmap.jp/w_yoshida/published_papers/31044279)

Hiramori, Daiki, and Saori Kamano. 2021. \"Asking about Sexual Orientation and Gender Identity in Social Surveys in Japan: Findings from the Osaka City Residents\' Survey and Related Preparatory Studies.\" *Journal of Population Problems*. 76(4): 443-66.（[郭水林・小西優実訳，2021，「性的指向と性自認のあり方を日本の量的調査でいかにとらえるか：大阪市民調査に向けた準備調査における項目の検討と本調査の結果」『人口問題研究』77(1): 45--67．](http://www.ipss.go.jp/syoushika/bunken/data/pdf/21770104.pdf)）

[松林哲也，2017，「期日前投票制度と投票率」『選挙研究』33(2): 58--72．](https://doi.org/10.14854/jaes.33.2_58)

[深井太洋，2019，「保育所整備は女性の就業率や出生率を上げたのか：保育所整備の政策評価」『日本労働研究雑誌』708: 4--20．](https://www.jil.go.jp/institute/zassi/backnumber/2019/06/pdf/004-020.pdf)

1週につき2本を指定し、それぞれレジュメ担当者を置いた。いずれも形式は先ほどと同様にした。論文の選択基準は、問い（目的）が明確に提示され、論文の標準的な型にしたがい、回帰分析あるいはそれに準ずる分析手法を用いて書かれ、かつ過度に専門的でないかというのを基準にした。これが意外と難しく、自分が今まで書いた論文のなかで残念ながらここに入るものではなかったので、少し反省した。

Hiramori & Kamano (2021)は回帰分析を使っているという基準に当てはまらないが、何らかの概念を測定することの難しさを教えてくれる点で非常によい論文であること、また現代的で関心を引くテーマだと判断したので、取り上げることにした。深井（2019）はレビュー論文のためやはりこの基準には当てはまらないが、この種の論文はテーマ探しをする際に有用であるし、またテーマも興味深いと判断したので、取り上げることにした。

いずれも専門的な学術誌に掲載された論文であり、（とりわけ統計について勉強していない）大学1年生にとってはその内容を正確に理解し批判的な読解をするのは難しいかもしれない。しかし、きちんと書かれた論文というのはレポートや論文というのがどういう文章なのかを理解する良い教材であるし、実は計量分析を使っているといっても、本文自体は難しい計量分析の方法を知らなくても理解できるように書いてあることが多い。扱っているテーマはいずれも現代社会に関係するトピックであるし、いきなり『プロテスタンティズムの倫理と資本主義の精神』とか『自殺論』とか読まされるよりはずっとわかりやすいだろうし、自分も楽しいので、論文購読を含めることにした。

もちろん、論文購読にあたって最低限の回帰分析の読み方については説明した。この分析が適切かどうかということについて侃々諤々の議論をする必要はまったくなく、どのような問いを立て、どのようなデータを使って、どのような主張をしているのかをつかむことを主眼に置くことにした。

担当してくれた学生のレジュメはいずれもよくまとまっていてコメントも的確であった。過度にテクニカルな論文を選ばないよう注意しないといけないが、なかなか悪くないと思ったので、今後も論文購読は採用するかもしれない。採用する論文は、あまり自分の専門から離れすぎないほうがいいかもしれない------たとえば、松林（2017）のときは自分が投票制度とかに詳しくないために、あまり話を広げることができなかったという反省がある。一方でHiramori & Kamano（2021）は単純集計レベルの分析を行っているがゆえに、結果の値などから議論が広がることもある。多様なテーマをカバーするよりはむしろ、最新の論文であり、学生の関心をひくものでありながら、手法としては難しくない論文（そういう論文を探すのがかなり難しいわけだけど......）を選定できると、効果的ではないだろうか。

### 個人研究報告

PowerPointなどのスライドを使って、期末レポートの構想を報告してもらった。学生の関心は待機児童問題、少子化、自殺、子どもの貧困、日本の幸福度の低さ、政治家のジェンダーバランスなど、王道的な設定のものが多かったように思う。

インターネットで当該のテーマについて調べて出てくる白書の情報などを紹介するというふうな構成の報告が多かった（ファーストステップとして白書を参照するのはよいと思う）。学生の多くはちゃんと準備して報告していることが見て取れ、感心しながら聞いていた。

学生からは、「他の国と比較してみるといいんじゃないか」というコメントや「現在どのような政策（解決策）が取られているのか、どのような政策が必要なのか」というふうな方向性のコメントが出ることが多かった。こうしたコメントが効果的に働くかそうでないかは場合によると思うが、解決志向で考える学生が多いというのは個人的には学ぶところがあった。実証的な研究を行うとき、国際比較には慎重になりがちである。そもそも異なる国で○○が比較可能かどうか慎重に考えないといけないし、比較対象とする国も慎重に選ぶ必要がある。また、どのような政策が効果的かというよりは、今実施されている政策が効果があったかどうか、といった過去の事実にもとづいて実証がなされることが普通である。自分が10数年前に社会問題に対してどのような見方をしていたのかわからないが、実証的な見方というのは意識して訓練しないと出てきにくい発想なのかなと思った。

自分からは、テーマをより絞り込んでいこうということと、出典をきちんと書こうということ、あるいはこういう比較をすると良いんじゃないか、というようなコメントをすることが多かった。自分の研究領域に近い内容の報告については参考になりそうな新書などを紹介したりした。

## 所感

人文学寄りの関心に即した文献購読やレポート・論文の書き方に関する話はほとんどできなかった。たとえば倫理学や歴史学、哲学のような分野の論文も取り上げても良かったのかもしれない。ただ自分はまったくの専門外であり、その論文について解説したりするのは自分の能力の範囲を越えているので、悩ましいところ。

活発な議論というのはあまり起こらなかった。自分から手を挙げて発言する人というのは多くなく、基本的には教員から指名して喋ってもらうことが多かった。ただ、当てれば何かは喋ってくれるし、おもしろい発言もたびたびあったので、その意味ではまったくにっちもさっちもいかなくなるといったことはなかった。といっても、大学1年で自分からどんどん手を挙げて発言する学生のほうが珍しいので（自分も学部1年のころとかは何を喋っていいのかわからなかったので黙っていた）、そこまで気にする必要はないのかもしれない。とはいえ学生同士ではよく喋ってくれるという印象はあるので、グループワークをするなどの工夫があるといいかもしれない。

あとは、文章を書くうえでどのように引用と自分の主張を分けるかをもっと説明してもよかった。たとえば実際に1000字くらいの小レポートを書いてもらって、ここはどの部分が引用なのかわからないねとか、引用と自分の主張が分けられていないねとか、参考文献の書き方がこれだと不十分だねとか、ここは論理的につながっていないねというようなことを実際に授業中に添削したりとかするのはあってもいいのかもしれない。

後期も似たような授業があるので、そのときに、あるいは今後、今回の経験を少しでも活かせると良いと思う。
